version: "3.9"

services:
  server:
    container_name: mirthgraph-server
    build:
      context: ./server/
    ports:
      - 3000:3000
    networks:
      m:
    volumes:
      - /usr/share/mirthgraph/public:/usr/src/app/public
    depends_on:
      - redis
    restart: always
  frontend:
    container_name: mirthgraph-frontend
    build:
      context: ./frontend/
    networks:
      m:
    ports:
      - 80:80
    depends_on:
      - server
    restart: always
  redis:
    container_name: mirthgraph-redis
    image: redis:latest
    networks:
      - m
    ports:
      - 6379:6379
    restart: always
networks:
  m:
