services:
  mirthgraph:
    image: ${DOCKER_REGISTRY-}mirthgraph
    build:
      context: mirthgraph
      dockerfile: Dockerfile
    ports:
    - "9001:8081"
    depends_on:
    - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres