services:
  mirthgraph:
    image: ${DOCKER_REGISTRY-}mirthgraph
    build:
      context: mirthgraph
      dockerfile: Dockerfile
    ports:
    - "9001:8081"
    depends_on:
    - redis
    - postgres
    extra_hosts:
    - "host.docker.internal:host-gateway"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mirthgraph
      POSTGRES_DB: mirthgraph
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "9003:5540"
    depends_on:
    - redis
  adminer:
    image: adminer
    restart: always
    ports:
      - 9002:8080
    depends_on:
    - postgres