version: "3.9"

services:
  server:
    container_name: mirthgraph-server
    build:
      context: ./server/
    ports:
      - 3000:3000
    networks:
      m:
        aliases:
          - server.localhost
    depends_on:
      - redis
  frontend:
    container_name: mirthgraph-frontend
    build:
      context: ./frontend/
    networks:
      m:
        aliases:
          - frontend.localhost
    ports:
      - 80:80
    depends_on:
      - server
  redis:
    container_name: mirthgraph-redis
    image: redis:latest
    networks:
      - m
    ports:
      - 6379:6379

networks:
  m:
