[package]
name = "mirthgraph"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
progenitor-client = { git = "https://github.com/oxidecomputer/progenitor" }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }
regress = "0.10"
api = { path = "api" }
axum = { version = "0.8", features = ["macros"] }
tokio = { version = "1.48", features = ["full"] }

[build-dependencies]
prettyplease = "0.2"
progenitor = { git = "https://github.com/oxidecomputer/progenitor" }
serde_json = "1.0"
syn = "2.0"

[workspace]
members = ["api"]
