/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`clear_all_statistics`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClearAllStatisticsError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`clear_statistics`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClearStatisticsError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_statistics`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatisticsError {
    DefaultResponse(Vec<models::ChannelStatistics>),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_statistics1`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatistics1Error {
    DefaultResponse(models::ChannelStatistics),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_statistics_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetStatisticsPostError {
    DefaultResponse(Vec<models::ChannelStatistics>),
    UnknownValue(serde_json::Value),
}


pub async fn clear_all_statistics(configuration: &configuration::Configuration, ) -> Result<(), Error<ClearAllStatisticsError>> {

    let uri_str = format!("{}/channels/_clearAllStatistics", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ClearAllStatisticsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn clear_statistics(configuration: &configuration::Configuration, request_body: std::collections::HashMap<String, Vec<i32>>, received: Option<bool>, filtered: Option<bool>, sent: Option<bool>, error: Option<bool>) -> Result<(), Error<ClearStatisticsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_request_body = request_body;
    let p_query_received = received;
    let p_query_filtered = filtered;
    let p_query_sent = sent;
    let p_query_error = error;

    let uri_str = format!("{}/channels/_clearStatistics", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_received {
        req_builder = req_builder.query(&[("received", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filtered {
        req_builder = req_builder.query(&[("filtered", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sent {
        req_builder = req_builder.query(&[("sent", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_error {
        req_builder = req_builder.query(&[("error", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ClearStatisticsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_statistics(configuration: &configuration::Configuration, channel_id: Option<Vec<String>>, include_undeployed: Option<bool>, include_metadata_id: Option<Vec<i32>>, exclude_metadata_id: Option<Vec<i32>>, aggregate_stats: Option<bool>) -> Result<Vec<models::ChannelStatistics>, Error<GetStatisticsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_query_include_undeployed = include_undeployed;
    let p_query_include_metadata_id = include_metadata_id;
    let p_query_exclude_metadata_id = exclude_metadata_id;
    let p_query_aggregate_stats = aggregate_stats;

    let uri_str = format!("{}/channels/statistics", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_channel_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("channelId".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("channelId", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_include_undeployed {
        req_builder = req_builder.query(&[("includeUndeployed", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_metadata_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("includeMetadataId".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("includeMetadataId", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_exclude_metadata_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("excludeMetadataId".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("excludeMetadataId", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_aggregate_stats {
        req_builder = req_builder.query(&[("aggregateStats", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ChannelStatistics&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ChannelStatistics&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatisticsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_statistics1(configuration: &configuration::Configuration, channel_id: &str) -> Result<models::ChannelStatistics, Error<GetStatistics1Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_channel_id = channel_id;

    let uri_str = format!("{}/channels/{channelId}/statistics", configuration.base_path, channelId=crate::apis::urlencode(p_path_channel_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ChannelStatistics`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ChannelStatistics`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatistics1Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_statistics_post(configuration: &configuration::Configuration, channel_ids: Option<Vec<String>>, include_undeployed: Option<bool>, include_metadata_ids: Option<Vec<i32>>, exclude_metadata_ids: Option<Vec<i32>>, aggregate_stats: Option<bool>) -> Result<Vec<models::ChannelStatistics>, Error<GetStatisticsPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_channel_ids = channel_ids;
    let p_form_include_undeployed = include_undeployed;
    let p_form_include_metadata_ids = include_metadata_ids;
    let p_form_exclude_metadata_ids = exclude_metadata_ids;
    let p_form_aggregate_stats = aggregate_stats;

    let uri_str = format!("{}/channels/statistics/_getStatistics", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form = reqwest::multipart::Form::new();
    if let Some(param_value) = p_form_channel_ids {
        multipart_form = multipart_form.text("channelIds", param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string());
    }
    if let Some(param_value) = p_form_include_undeployed {
        multipart_form = multipart_form.text("includeUndeployed", param_value.to_string());
    }
    if let Some(param_value) = p_form_include_metadata_ids {
        multipart_form = multipart_form.text("includeMetadataIds", param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string());
    }
    if let Some(param_value) = p_form_exclude_metadata_ids {
        multipart_form = multipart_form.text("excludeMetadataIds", param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string());
    }
    if let Some(param_value) = p_form_aggregate_stats {
        multipart_form = multipart_form.text("aggregateStats", param_value.to_string());
    }
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ChannelStatistics&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ChannelStatistics&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetStatisticsPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

