/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`cache_wsdl_from_url`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CacheWsdlFromUrlError {
    DefaultResponse(serde_json::Value),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_template`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTemplateError {
    DefaultResponse(Vec<String>),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`generate_envelope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GenerateEnvelopeError {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_definition`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetDefinitionError {
    DefaultResponse(models::DefinitionServiceMap),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_soap_action`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSoapActionError {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_tables`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTablesError {
    DefaultResponse(Vec<models::Table>),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_template`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTemplateError {
    DefaultResponse(models::JmsConnectorProperties),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_templates`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTemplatesError {
    DefaultResponse(std::collections::HashMap<String, models::JmsConnectorProperties>),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`is_wsdl_cached`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IsWsdlCachedError {
    DefaultResponse(bool),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`save_template`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SaveTemplateError {
    DefaultResponse(Vec<String>),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`send_test_email`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SendTestEmailError {
    DefaultResponse(models::ConnectionTestResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`test_connection`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TestConnectionError {
    DefaultResponse(models::ConnectionTestResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`test_connection1`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TestConnection1Error {
    DefaultResponse(models::ConnectionTestResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`test_connection2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TestConnection2Error {
    DefaultResponse(models::ConnectionTestResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`test_read`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TestReadError {
    DefaultResponse(models::ConnectionTestResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`test_write`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TestWriteError {
    DefaultResponse(models::ConnectionTestResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`test_write1`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TestWrite1Error {
    DefaultResponse(models::ConnectionTestResponse),
    UnknownValue(serde_json::Value),
}


pub async fn cache_wsdl_from_url(configuration: &configuration::Configuration, channel_id: &str, web_service_dispatcher_properties: models::WebServiceDispatcherProperties, channel_name: Option<&str>) -> Result<serde_json::Value, Error<CacheWsdlFromUrlError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_body_web_service_dispatcher_properties = web_service_dispatcher_properties;
    let p_query_channel_name = channel_name;

    let uri_str = format!("{}/connectors/ws/_cacheWsdlFromUrl", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("channelId", &p_query_channel_id.to_string())]);
    if let Some(ref param_value) = p_query_channel_name {
        req_builder = req_builder.query(&[("channelName", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_web_service_dispatcher_properties);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CacheWsdlFromUrlError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_template(configuration: &configuration::Configuration, template_name: &str) -> Result<Vec<String>, Error<DeleteTemplateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_template_name = template_name;

    let uri_str = format!("{}/connectors/jms/templates/{templateName}", configuration.base_path, templateName=crate::apis::urlencode(p_path_template_name));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;String&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;String&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTemplateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn generate_envelope(configuration: &configuration::Configuration, channel_id: &str, wsdl_url: &str, service: &str, port: &str, operation: &str, channel_name: Option<&str>, username: Option<&str>, password: Option<&str>, build_optional: Option<bool>) -> Result<String, Error<GenerateEnvelopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_channel_id = channel_id;
    let p_form_wsdl_url = wsdl_url;
    let p_form_service = service;
    let p_form_port = port;
    let p_form_operation = operation;
    let p_form_channel_name = channel_name;
    let p_form_username = username;
    let p_form_password = password;
    let p_form_build_optional = build_optional;

    let uri_str = format!("{}/connectors/ws/_generateEnvelope", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("channelId", p_form_channel_id.to_string());
    if let Some(param_value) = p_form_channel_name {
        multipart_form_params.insert("channelName", param_value.to_string());
    }
    multipart_form_params.insert("wsdlUrl", p_form_wsdl_url.to_string());
    if let Some(param_value) = p_form_username {
        multipart_form_params.insert("username", param_value.to_string());
    }
    if let Some(param_value) = p_form_password {
        multipart_form_params.insert("password", param_value.to_string());
    }
    multipart_form_params.insert("service", p_form_service.to_string());
    multipart_form_params.insert("port", p_form_port.to_string());
    multipart_form_params.insert("operation", p_form_operation.to_string());
    if let Some(param_value) = p_form_build_optional {
        multipart_form_params.insert("buildOptional", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GenerateEnvelopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_definition(configuration: &configuration::Configuration, channel_id: &str, wsdl_url: &str, channel_name: Option<&str>, username: Option<&str>, password: Option<&str>) -> Result<models::DefinitionServiceMap, Error<GetDefinitionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_channel_id = channel_id;
    let p_form_wsdl_url = wsdl_url;
    let p_form_channel_name = channel_name;
    let p_form_username = username;
    let p_form_password = password;

    let uri_str = format!("{}/connectors/ws/_getDefinition", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("channelId", p_form_channel_id.to_string());
    if let Some(param_value) = p_form_channel_name {
        multipart_form_params.insert("channelName", param_value.to_string());
    }
    multipart_form_params.insert("wsdlUrl", p_form_wsdl_url.to_string());
    if let Some(param_value) = p_form_username {
        multipart_form_params.insert("username", param_value.to_string());
    }
    if let Some(param_value) = p_form_password {
        multipart_form_params.insert("password", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DefinitionServiceMap`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DefinitionServiceMap`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetDefinitionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_soap_action(configuration: &configuration::Configuration, channel_id: &str, wsdl_url: &str, service: &str, port: &str, operation: &str, channel_name: Option<&str>, username: Option<&str>, password: Option<&str>) -> Result<String, Error<GetSoapActionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_channel_id = channel_id;
    let p_form_wsdl_url = wsdl_url;
    let p_form_service = service;
    let p_form_port = port;
    let p_form_operation = operation;
    let p_form_channel_name = channel_name;
    let p_form_username = username;
    let p_form_password = password;

    let uri_str = format!("{}/connectors/ws/_getSoapAction", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("channelId", p_form_channel_id.to_string());
    if let Some(param_value) = p_form_channel_name {
        multipart_form_params.insert("channelName", param_value.to_string());
    }
    multipart_form_params.insert("wsdlUrl", p_form_wsdl_url.to_string());
    if let Some(param_value) = p_form_username {
        multipart_form_params.insert("username", param_value.to_string());
    }
    if let Some(param_value) = p_form_password {
        multipart_form_params.insert("password", param_value.to_string());
    }
    multipart_form_params.insert("service", p_form_service.to_string());
    multipart_form_params.insert("port", p_form_port.to_string());
    multipart_form_params.insert("operation", p_form_operation.to_string());
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSoapActionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_tables(configuration: &configuration::Configuration, channel_id: &str, channel_name: &str, driver: &str, url: &str, username: Option<&str>, password: Option<&str>, table_name_pattern: Option<Vec<String>>, select_limit: Option<&str>, resource_id: Option<Vec<String>>) -> Result<Vec<models::Table>, Error<GetTablesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_query_channel_name = channel_name;
    let p_query_driver = driver;
    let p_query_url = url;
    let p_query_username = username;
    let p_query_password = password;
    let p_query_table_name_pattern = table_name_pattern;
    let p_query_select_limit = select_limit;
    let p_query_resource_id = resource_id;

    let uri_str = format!("{}/connectors/jdbc/_getTables", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("channelId", &p_query_channel_id.to_string())]);
    req_builder = req_builder.query(&[("channelName", &p_query_channel_name.to_string())]);
    req_builder = req_builder.query(&[("driver", &p_query_driver.to_string())]);
    req_builder = req_builder.query(&[("url", &p_query_url.to_string())]);
    if let Some(ref param_value) = p_query_username {
        req_builder = req_builder.query(&[("username", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_password {
        req_builder = req_builder.query(&[("password", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_table_name_pattern {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("tableNamePattern".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("tableNamePattern", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_select_limit {
        req_builder = req_builder.query(&[("selectLimit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_resource_id {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("resourceId".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("resourceId", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Table&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Table&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTablesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_template(configuration: &configuration::Configuration, template_name: &str) -> Result<models::JmsConnectorProperties, Error<GetTemplateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_template_name = template_name;

    let uri_str = format!("{}/connectors/jms/templates/{templateName}", configuration.base_path, templateName=crate::apis::urlencode(p_path_template_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::JmsConnectorProperties`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::JmsConnectorProperties`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTemplateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_templates(configuration: &configuration::Configuration, ) -> Result<std::collections::HashMap<String, models::JmsConnectorProperties>, Error<GetTemplatesError>> {

    let uri_str = format!("{}/connectors/jms/templates", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::JmsConnectorProperties&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::JmsConnectorProperties&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTemplatesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn is_wsdl_cached(configuration: &configuration::Configuration, channel_id: &str, wsdl_url: &str, channel_name: Option<&str>, username: Option<&str>, password: Option<&str>) -> Result<bool, Error<IsWsdlCachedError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_channel_id = channel_id;
    let p_form_wsdl_url = wsdl_url;
    let p_form_channel_name = channel_name;
    let p_form_username = username;
    let p_form_password = password;

    let uri_str = format!("{}/connectors/ws/_isWsdlCached", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("channelId", p_form_channel_id.to_string());
    if let Some(param_value) = p_form_channel_name {
        multipart_form_params.insert("channelName", param_value.to_string());
    }
    multipart_form_params.insert("wsdlUrl", p_form_wsdl_url.to_string());
    if let Some(param_value) = p_form_username {
        multipart_form_params.insert("username", param_value.to_string());
    }
    if let Some(param_value) = p_form_password {
        multipart_form_params.insert("password", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `bool`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `bool`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<IsWsdlCachedError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn save_template(configuration: &configuration::Configuration, template_name: &str, jms_connector_properties: models::JmsConnectorProperties) -> Result<Vec<String>, Error<SaveTemplateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_template_name = template_name;
    let p_body_jms_connector_properties = jms_connector_properties;

    let uri_str = format!("{}/connectors/jms/templates/{templateName}", configuration.base_path, templateName=crate::apis::urlencode(p_path_template_name));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_jms_connector_properties);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;String&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;String&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SaveTemplateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn send_test_email(configuration: &configuration::Configuration, channel_id: &str, channel_name: &str, smtp_dispatcher_properties: models::SmtpDispatcherProperties) -> Result<models::ConnectionTestResponse, Error<SendTestEmailError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_query_channel_name = channel_name;
    let p_body_smtp_dispatcher_properties = smtp_dispatcher_properties;

    let uri_str = format!("{}/connectors/smtp/_sendTestEmail", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("channelId", &p_query_channel_id.to_string())]);
    req_builder = req_builder.query(&[("channelName", &p_query_channel_name.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_smtp_dispatcher_properties);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectionTestResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectionTestResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SendTestEmailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn test_connection(configuration: &configuration::Configuration, channel_id: &str, channel_name: &str, http_dispatcher_properties: models::HttpDispatcherProperties) -> Result<models::ConnectionTestResponse, Error<TestConnectionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_query_channel_name = channel_name;
    let p_body_http_dispatcher_properties = http_dispatcher_properties;

    let uri_str = format!("{}/connectors/http/_testConnection", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("channelId", &p_query_channel_id.to_string())]);
    req_builder = req_builder.query(&[("channelName", &p_query_channel_name.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_http_dispatcher_properties);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectionTestResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectionTestResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TestConnectionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn test_connection1(configuration: &configuration::Configuration, channel_id: &str, channel_name: &str, tcp_dispatcher_properties: models::TcpDispatcherProperties) -> Result<models::ConnectionTestResponse, Error<TestConnection1Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_query_channel_name = channel_name;
    let p_body_tcp_dispatcher_properties = tcp_dispatcher_properties;

    let uri_str = format!("{}/connectors/tcp/_testConnection", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("channelId", &p_query_channel_id.to_string())]);
    req_builder = req_builder.query(&[("channelName", &p_query_channel_name.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_tcp_dispatcher_properties);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectionTestResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectionTestResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TestConnection1Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn test_connection2(configuration: &configuration::Configuration, channel_id: &str, web_service_dispatcher_properties: models::WebServiceDispatcherProperties, channel_name: Option<&str>) -> Result<models::ConnectionTestResponse, Error<TestConnection2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_body_web_service_dispatcher_properties = web_service_dispatcher_properties;
    let p_query_channel_name = channel_name;

    let uri_str = format!("{}/connectors/ws/_testConnection", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("channelId", &p_query_channel_id.to_string())]);
    if let Some(ref param_value) = p_query_channel_name {
        req_builder = req_builder.query(&[("channelName", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_web_service_dispatcher_properties);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectionTestResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectionTestResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TestConnection2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn test_read(configuration: &configuration::Configuration, channel_id: &str, channel_name: &str, file_receiver_properties: models::FileReceiverProperties) -> Result<models::ConnectionTestResponse, Error<TestReadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_query_channel_name = channel_name;
    let p_body_file_receiver_properties = file_receiver_properties;

    let uri_str = format!("{}/connectors/file/_testRead", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("channelId", &p_query_channel_id.to_string())]);
    req_builder = req_builder.query(&[("channelName", &p_query_channel_name.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_file_receiver_properties);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectionTestResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectionTestResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TestReadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn test_write(configuration: &configuration::Configuration, channel_id: &str, channel_name: &str, body: &str) -> Result<models::ConnectionTestResponse, Error<TestWriteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_query_channel_name = channel_name;
    let p_body_body = body;

    let uri_str = format!("{}/connectors/doc/_testWrite", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("channelId", &p_query_channel_id.to_string())]);
    req_builder = req_builder.query(&[("channelName", &p_query_channel_name.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectionTestResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectionTestResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TestWriteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn test_write1(configuration: &configuration::Configuration, channel_id: &str, channel_name: &str, file_dispatcher_properties: models::FileDispatcherProperties) -> Result<models::ConnectionTestResponse, Error<TestWrite1Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_channel_id = channel_id;
    let p_query_channel_name = channel_name;
    let p_body_file_dispatcher_properties = file_dispatcher_properties;

    let uri_str = format!("{}/connectors/file/_testWrite", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("channelId", &p_query_channel_id.to_string())]);
    req_builder = req_builder.query(&[("channelName", &p_query_channel_name.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_body_file_dispatcher_properties);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConnectionTestResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConnectionTestResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TestWrite1Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

