/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertModel {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "trigger", skip_serializing_if = "Option::is_none")]
    pub trigger: Option<Box<models::AlertTrigger>>,
    #[serde(rename = "actionGroups", skip_serializing_if = "Option::is_none")]
    pub action_groups: Option<Vec<models::AlertActionGroup>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl AlertModel {
    pub fn new() -> AlertModel {
        AlertModel {
            id: None,
            name: None,
            enabled: None,
            trigger: None,
            action_groups: None,
            properties: None,
            purged_properties: None,
        }
    }
}

