/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertInfo {
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::AlertModel>>,
    #[serde(rename = "protocolOptions", skip_serializing_if = "Option::is_none")]
    pub protocol_options: Option<std::collections::HashMap<String, std::collections::HashMap<String, String>>>,
    #[serde(rename = "changedChannels", skip_serializing_if = "Option::is_none")]
    pub changed_channels: Option<Vec<models::ChannelSummary>>,
}

impl AlertInfo {
    pub fn new() -> AlertInfo {
        AlertInfo {
            model: None,
            protocol_options: None,
            changed_channels: None,
        }
    }
}

