/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertAction {
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<String>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl AlertAction {
    pub fn new() -> AlertAction {
        AlertAction {
            protocol: None,
            recipient: None,
            purged_properties: None,
        }
    }
}

