/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiProvider {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "minVersion", skip_serializing_if = "Option::is_none")]
    pub min_version: Option<String>,
    #[serde(rename = "maxVersion", skip_serializing_if = "Option::is_none")]
    pub max_version: Option<String>,
}

impl ApiProvider {
    pub fn new() -> ApiProvider {
        ApiProvider {
            r#type: None,
            name: None,
            min_version: None,
            max_version: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "SERVLET_INTERFACE_PACKAGE")]
    ServletInterfacePackage,
    #[serde(rename = "SERVLET_INTERFACE")]
    ServletInterface,
    #[serde(rename = "CORE_PACKAGE")]
    CorePackage,
    #[serde(rename = "SERVER_PACKAGE")]
    ServerPackage,
    #[serde(rename = "CORE_CLASS")]
    CoreClass,
    #[serde(rename = "SERVER_CLASS")]
    ServerClass,
}

impl Default for Type {
    fn default() -> Type {
        Self::ServletInterfacePackage
    }
}

