/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelHeader {
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<i32>,
    #[serde(rename = "deployedDate", skip_serializing_if = "Option::is_none")]
    pub deployed_date: Option<String>,
    #[serde(rename = "codeTemplatesChanged", skip_serializing_if = "Option::is_none")]
    pub code_templates_changed: Option<bool>,
}

impl ChannelHeader {
    pub fn new() -> ChannelHeader {
        ChannelHeader {
            revision: None,
            deployed_date: None,
            code_templates_changed: None,
        }
    }
}

