/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelProperties {
    #[serde(rename = "clearGlobalChannelMap", skip_serializing_if = "Option::is_none")]
    pub clear_global_channel_map: Option<bool>,
    #[serde(rename = "messageStorageMode", skip_serializing_if = "Option::is_none")]
    pub message_storage_mode: Option<MessageStorageMode>,
    #[serde(rename = "encryptAttachments", skip_serializing_if = "Option::is_none")]
    pub encrypt_attachments: Option<bool>,
    #[serde(rename = "encryptCustomMetaData", skip_serializing_if = "Option::is_none")]
    pub encrypt_custom_meta_data: Option<bool>,
    #[serde(rename = "removeContentOnCompletion", skip_serializing_if = "Option::is_none")]
    pub remove_content_on_completion: Option<bool>,
    #[serde(rename = "removeOnlyFilteredOnCompletion", skip_serializing_if = "Option::is_none")]
    pub remove_only_filtered_on_completion: Option<bool>,
    #[serde(rename = "removeAttachmentsOnCompletion", skip_serializing_if = "Option::is_none")]
    pub remove_attachments_on_completion: Option<bool>,
    #[serde(rename = "initialState", skip_serializing_if = "Option::is_none")]
    pub initial_state: Option<InitialState>,
    #[serde(rename = "storeAttachments", skip_serializing_if = "Option::is_none")]
    pub store_attachments: Option<bool>,
    #[serde(rename = "metaDataColumns", skip_serializing_if = "Option::is_none")]
    pub meta_data_columns: Option<Vec<models::MetaDataColumn>>,
    #[serde(rename = "attachmentProperties", skip_serializing_if = "Option::is_none")]
    pub attachment_properties: Option<Box<models::AttachmentHandlerProperties>>,
    #[serde(rename = "resourceIds", skip_serializing_if = "Option::is_none")]
    pub resource_ids: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "encryptMessageContent", skip_serializing_if = "Option::is_none")]
    pub encrypt_message_content: Option<bool>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ChannelProperties {
    pub fn new() -> ChannelProperties {
        ChannelProperties {
            clear_global_channel_map: None,
            message_storage_mode: None,
            encrypt_attachments: None,
            encrypt_custom_meta_data: None,
            remove_content_on_completion: None,
            remove_only_filtered_on_completion: None,
            remove_attachments_on_completion: None,
            initial_state: None,
            store_attachments: None,
            meta_data_columns: None,
            attachment_properties: None,
            resource_ids: None,
            encrypt_message_content: None,
            purged_properties: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessageStorageMode {
    #[serde(rename = "DEVELOPMENT")]
    Development,
    #[serde(rename = "PRODUCTION")]
    Production,
    #[serde(rename = "RAW")]
    Raw,
    #[serde(rename = "METADATA")]
    Metadata,
    #[serde(rename = "DISABLED")]
    Disabled,
}

impl Default for MessageStorageMode {
    fn default() -> MessageStorageMode {
        Self::Development
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InitialState {
    #[serde(rename = "Undeployed")]
    Undeployed,
    #[serde(rename = "Deploying")]
    Deploying,
    #[serde(rename = "Undeploying")]
    Undeploying,
    #[serde(rename = "Starting")]
    Starting,
    #[serde(rename = "Started")]
    Started,
    #[serde(rename = "Pausing")]
    Pausing,
    #[serde(rename = "Paused")]
    Paused,
    #[serde(rename = "Stopping")]
    Stopping,
    #[serde(rename = "Stopped")]
    Stopped,
    #[serde(rename = "Syncing")]
    Syncing,
    #[serde(rename = "Unknown")]
    Unknown,
}

impl Default for InitialState {
    fn default() -> InitialState {
        Self::Undeployed
    }
}

