/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelSummary {
    #[serde(rename = "channelId", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    #[serde(rename = "undeployed", skip_serializing_if = "Option::is_none")]
    pub undeployed: Option<bool>,
    #[serde(rename = "channelStatus", skip_serializing_if = "Option::is_none")]
    pub channel_status: Option<Box<models::ChannelStatus>>,
}

impl ChannelSummary {
    pub fn new() -> ChannelSummary {
        ChannelSummary {
            channel_id: None,
            deleted: None,
            undeployed: None,
            channel_status: None,
        }
    }
}

