/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelStatistics {
    #[serde(rename = "serverId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(rename = "channelId", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "received", skip_serializing_if = "Option::is_none")]
    pub received: Option<i64>,
    #[serde(rename = "sent", skip_serializing_if = "Option::is_none")]
    pub sent: Option<i64>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<i64>,
    #[serde(rename = "filtered", skip_serializing_if = "Option::is_none")]
    pub filtered: Option<i64>,
    #[serde(rename = "queued", skip_serializing_if = "Option::is_none")]
    pub queued: Option<i64>,
}

impl ChannelStatistics {
    pub fn new() -> ChannelStatistics {
        ChannelStatistics {
            server_id: None,
            channel_id: None,
            received: None,
            sent: None,
            error: None,
            filtered: None,
            queued: None,
        }
    }
}

