/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelPruningSettings {
    #[serde(rename = "pruneMetaDataDays", skip_serializing_if = "Option::is_none")]
    pub prune_meta_data_days: Option<i32>,
    #[serde(rename = "pruneContentDays", skip_serializing_if = "Option::is_none")]
    pub prune_content_days: Option<i32>,
    #[serde(rename = "archiveEnabled", skip_serializing_if = "Option::is_none")]
    pub archive_enabled: Option<bool>,
    #[serde(rename = "pruneErroredMessages", skip_serializing_if = "Option::is_none")]
    pub prune_errored_messages: Option<bool>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ChannelPruningSettings {
    pub fn new() -> ChannelPruningSettings {
        ChannelPruningSettings {
            prune_meta_data_days: None,
            prune_content_days: None,
            archive_enabled: None,
            prune_errored_messages: None,
            purged_properties: None,
        }
    }
}

