/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelExportData {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::ChannelMetadata>>,
    #[serde(rename = "codeTemplateLibraries", skip_serializing_if = "Option::is_none")]
    pub code_template_libraries: Option<Vec<models::CodeTemplateLibrary>>,
    #[serde(rename = "dependentIds", skip_serializing_if = "Option::is_none")]
    pub dependent_ids: Option<Vec<String>>,
    #[serde(rename = "dependencyIds", skip_serializing_if = "Option::is_none")]
    pub dependency_ids: Option<Vec<String>>,
    #[serde(rename = "channelTags", skip_serializing_if = "Option::is_none")]
    pub channel_tags: Option<Vec<models::ChannelTag>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ChannelExportData {
    pub fn new() -> ChannelExportData {
        ChannelExportData {
            metadata: None,
            code_template_libraries: None,
            dependent_ids: None,
            dependency_ids: None,
            channel_tags: None,
            purged_properties: None,
        }
    }
}

