/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelTagBackgroundColor {
    #[serde(rename = "red", skip_serializing_if = "Option::is_none")]
    pub red: Option<i32>,
    #[serde(rename = "green", skip_serializing_if = "Option::is_none")]
    pub green: Option<i32>,
    #[serde(rename = "blue", skip_serializing_if = "Option::is_none")]
    pub blue: Option<i32>,
    #[serde(rename = "alpha", skip_serializing_if = "Option::is_none")]
    pub alpha: Option<i32>,
    #[serde(rename = "rgb", skip_serializing_if = "Option::is_none")]
    pub rgb: Option<i32>,
    #[serde(rename = "colorSpace", skip_serializing_if = "Option::is_none")]
    pub color_space: Option<Box<models::ChannelTagBackgroundColorColorSpace>>,
    #[serde(rename = "transparency", skip_serializing_if = "Option::is_none")]
    pub transparency: Option<i32>,
}

impl ChannelTagBackgroundColor {
    pub fn new() -> ChannelTagBackgroundColor {
        ChannelTagBackgroundColor {
            red: None,
            green: None,
            blue: None,
            alpha: None,
            rgb: None,
            color_space: None,
            transparency: None,
        }
    }
}

