/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelStatus {
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Box<models::Channel>>,
    #[serde(rename = "deployedDate", skip_serializing_if = "Option::is_none")]
    pub deployed_date: Option<String>,
    #[serde(rename = "deployedRevisionDelta", skip_serializing_if = "Option::is_none")]
    pub deployed_revision_delta: Option<i32>,
    #[serde(rename = "codeTemplatesChanged", skip_serializing_if = "Option::is_none")]
    pub code_templates_changed: Option<bool>,
    #[serde(rename = "localChannelId", skip_serializing_if = "Option::is_none")]
    pub local_channel_id: Option<i64>,
}

impl ChannelStatus {
    pub fn new() -> ChannelStatus {
        ChannelStatus {
            channel: None,
            deployed_date: None,
            deployed_revision_delta: None,
            code_templates_changed: None,
            local_channel_id: None,
        }
    }
}

