/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeTemplateProperties {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "functionDefinition", skip_serializing_if = "Option::is_none")]
    pub function_definition: Option<Box<models::CodeTemplateFunctionDefinition>>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "pluginPointName", skip_serializing_if = "Option::is_none")]
    pub plugin_point_name: Option<String>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl CodeTemplateProperties {
    pub fn new() -> CodeTemplateProperties {
        CodeTemplateProperties {
            r#type: None,
            description: None,
            function_definition: None,
            code: None,
            plugin_point_name: None,
            purged_properties: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Function")]
    Function,
    #[serde(rename = "Drag-and-Drop Code Block")]
    DragAndDropCodeBlock,
    #[serde(rename = "Compiled Code Block")]
    CompiledCodeBlock,
}

impl Default for Type {
    fn default() -> Type {
        Self::Function
    }
}

