/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeTemplateSummary {
    #[serde(rename = "codeTemplateId", skip_serializing_if = "Option::is_none")]
    pub code_template_id: Option<String>,
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    #[serde(rename = "codeTemplate", skip_serializing_if = "Option::is_none")]
    pub code_template: Option<Box<models::CodeTemplate>>,
}

impl CodeTemplateSummary {
    pub fn new() -> CodeTemplateSummary {
        CodeTemplateSummary {
            code_template_id: None,
            deleted: None,
            code_template: None,
        }
    }
}

