/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeTemplateLibrary {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<i32>,
    #[serde(rename = "lastModified", skip_serializing_if = "Option::is_none")]
    pub last_modified: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "includeNewChannels", skip_serializing_if = "Option::is_none")]
    pub include_new_channels: Option<bool>,
    #[serde(rename = "enabledChannelIds", skip_serializing_if = "Option::is_none")]
    pub enabled_channel_ids: Option<Vec<String>>,
    #[serde(rename = "disabledChannelIds", skip_serializing_if = "Option::is_none")]
    pub disabled_channel_ids: Option<Vec<String>>,
    #[serde(rename = "codeTemplates", skip_serializing_if = "Option::is_none")]
    pub code_templates: Option<Vec<models::CodeTemplate>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl CodeTemplateLibrary {
    pub fn new() -> CodeTemplateLibrary {
        CodeTemplateLibrary {
            id: None,
            name: None,
            revision: None,
            last_modified: None,
            description: None,
            include_new_channels: None,
            enabled_channel_ids: None,
            disabled_channel_ids: None,
            code_templates: None,
            purged_properties: None,
        }
    }
}

impl std::fmt::Display for CodeTemplateLibrary {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            serde_json::to_string(self).map_err(|_| std::fmt::Error)?
        )
    }
}
