/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionLogItem {
    #[serde(rename = "logId", skip_serializing_if = "Option::is_none")]
    pub log_id: Option<i64>,
    #[serde(rename = "serverId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(rename = "channelId", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "metadataId", skip_serializing_if = "Option::is_none")]
    pub metadata_id: Option<i64>,
    #[serde(rename = "dateAdded", skip_serializing_if = "Option::is_none")]
    pub date_added: Option<String>,
    #[serde(rename = "channelName", skip_serializing_if = "Option::is_none")]
    pub channel_name: Option<String>,
    #[serde(rename = "connectorType", skip_serializing_if = "Option::is_none")]
    pub connector_type: Option<String>,
    #[serde(rename = "eventState", skip_serializing_if = "Option::is_none")]
    pub event_state: Option<String>,
    #[serde(rename = "information", skip_serializing_if = "Option::is_none")]
    pub information: Option<String>,
}

impl ConnectionLogItem {
    pub fn new() -> ConnectionLogItem {
        ConnectionLogItem {
            log_id: None,
            server_id: None,
            channel_id: None,
            metadata_id: None,
            date_added: None,
            channel_name: None,
            connector_type: None,
            event_state: None,
            information: None,
        }
    }
}

