/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectorProperties {
    #[serde(rename = "pluginProperties", skip_serializing_if = "Option::is_none")]
    pub plugin_properties: Option<Vec<models::ConnectorPluginProperties>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ConnectorProperties {
    pub fn new() -> ConnectorProperties {
        ConnectorProperties {
            plugin_properties: None,
            name: None,
            protocol: None,
            purged_properties: None,
        }
    }
}

