/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionTestResponse {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "connectionInfo", skip_serializing_if = "Option::is_none")]
    pub connection_info: Option<String>,
}

impl ConnectionTestResponse {
    pub fn new() -> ConnectionTestResponse {
        ConnectionTestResponse {
            r#type: None,
            message: None,
            connection_info: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "SUCCESS")]
    Success,
    #[serde(rename = "TIME_OUT")]
    TimeOut,
    #[serde(rename = "FAILURE")]
    Failure,
}

impl Default for Type {
    fn default() -> Type {
        Self::Success
    }
}

