/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Connector {
    #[serde(rename = "metaDataId", skip_serializing_if = "Option::is_none")]
    pub meta_data_id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::ConnectorProperties>>,
    #[serde(rename = "transformer", skip_serializing_if = "Option::is_none")]
    pub transformer: Option<Box<models::Transformer>>,
    #[serde(rename = "responseTransformer", skip_serializing_if = "Option::is_none")]
    pub response_transformer: Option<Box<models::Transformer>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::Filter>>,
    #[serde(rename = "transportName", skip_serializing_if = "Option::is_none")]
    pub transport_name: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "waitForPrevious", skip_serializing_if = "Option::is_none")]
    pub wait_for_previous: Option<bool>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl Connector {
    pub fn new() -> Connector {
        Connector {
            meta_data_id: None,
            name: None,
            properties: None,
            transformer: None,
            response_transformer: None,
            filter: None,
            transport_name: None,
            mode: None,
            enabled: None,
            wait_for_previous: None,
            purged_properties: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "SOURCE")]
    Source,
    #[serde(rename = "DESTINATION")]
    Destination,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Source
    }
}

