/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardStatus {
    #[serde(rename = "channelId", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    #[serde(rename = "deployedRevisionDelta", skip_serializing_if = "Option::is_none")]
    pub deployed_revision_delta: Option<i32>,
    #[serde(rename = "deployedDate", skip_serializing_if = "Option::is_none")]
    pub deployed_date: Option<String>,
    #[serde(rename = "codeTemplatesChanged", skip_serializing_if = "Option::is_none")]
    pub code_templates_changed: Option<bool>,
    #[serde(rename = "statistics", skip_serializing_if = "Option::is_none")]
    pub statistics: Option<std::collections::HashMap<String, i64>>,
    #[serde(rename = "lifetimeStatistics", skip_serializing_if = "Option::is_none")]
    pub lifetime_statistics: Option<std::collections::HashMap<String, i64>>,
    #[serde(rename = "childStatuses", skip_serializing_if = "Option::is_none")]
    pub child_statuses: Option<Vec<models::DashboardStatus>>,
    #[serde(rename = "metaDataId", skip_serializing_if = "Option::is_none")]
    pub meta_data_id: Option<i32>,
    #[serde(rename = "queueEnabled", skip_serializing_if = "Option::is_none")]
    pub queue_enabled: Option<bool>,
    #[serde(rename = "queued", skip_serializing_if = "Option::is_none")]
    pub queued: Option<i64>,
    #[serde(rename = "waitForPrevious", skip_serializing_if = "Option::is_none")]
    pub wait_for_previous: Option<bool>,
    #[serde(rename = "statusType", skip_serializing_if = "Option::is_none")]
    pub status_type: Option<StatusType>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl DashboardStatus {
    pub fn new() -> DashboardStatus {
        DashboardStatus {
            channel_id: None,
            name: None,
            state: None,
            deployed_revision_delta: None,
            deployed_date: None,
            code_templates_changed: None,
            statistics: None,
            lifetime_statistics: None,
            child_statuses: None,
            meta_data_id: None,
            queue_enabled: None,
            queued: None,
            wait_for_previous: None,
            status_type: None,
            key: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "Undeployed")]
    Undeployed,
    #[serde(rename = "Deploying")]
    Deploying,
    #[serde(rename = "Undeploying")]
    Undeploying,
    #[serde(rename = "Starting")]
    Starting,
    #[serde(rename = "Started")]
    Started,
    #[serde(rename = "Pausing")]
    Pausing,
    #[serde(rename = "Paused")]
    Paused,
    #[serde(rename = "Stopping")]
    Stopping,
    #[serde(rename = "Stopped")]
    Stopped,
    #[serde(rename = "Syncing")]
    Syncing,
    #[serde(rename = "Unknown")]
    Unknown,
}

impl Default for State {
    fn default() -> State {
        Self::Undeployed
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusType {
    #[serde(rename = "CHANNEL")]
    Channel,
    #[serde(rename = "CHAIN")]
    Chain,
    #[serde(rename = "SOURCE_CONNECTOR")]
    SourceConnector,
    #[serde(rename = "DESTINATION_CONNECTOR")]
    DestinationConnector,
}

impl Default for StatusType {
    fn default() -> StatusType {
        Self::Channel
    }
}

