/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardChannelInfo {
    #[serde(rename = "dashboardStatuses", skip_serializing_if = "Option::is_none")]
    pub dashboard_statuses: Option<Vec<models::DashboardStatus>>,
    #[serde(rename = "remainingChannelIds", skip_serializing_if = "Option::is_none")]
    pub remaining_channel_ids: Option<Vec<String>>,
    #[serde(rename = "deployedChannelCount", skip_serializing_if = "Option::is_none")]
    pub deployed_channel_count: Option<i32>,
    #[serde(rename = "deployedChannelNames", skip_serializing_if = "Option::is_none")]
    pub deployed_channel_names: Option<i32>,
}

impl DashboardChannelInfo {
    pub fn new() -> DashboardChannelInfo {
        DashboardChannelInfo {
            dashboard_statuses: None,
            remaining_channel_ids: None,
            deployed_channel_count: None,
            deployed_channel_names: None,
        }
    }
}

