/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataTypeProperties {
    #[serde(rename = "serializationProperties", skip_serializing_if = "Option::is_none")]
    pub serialization_properties: Option<Box<models::SerializationProperties>>,
    #[serde(rename = "deserializationProperties", skip_serializing_if = "Option::is_none")]
    pub deserialization_properties: Option<Box<models::DeserializationProperties>>,
    #[serde(rename = "batchProperties", skip_serializing_if = "Option::is_none")]
    pub batch_properties: Option<Box<models::BatchProperties>>,
    #[serde(rename = "responseGenerationProperties", skip_serializing_if = "Option::is_none")]
    pub response_generation_properties: Option<Box<models::ResponseGenerationProperties>>,
    #[serde(rename = "responseValidationProperties", skip_serializing_if = "Option::is_none")]
    pub response_validation_properties: Option<Box<models::ResponseValidationProperties>>,
    #[serde(rename = "serializerProperties", skip_serializing_if = "Option::is_none")]
    pub serializer_properties: Option<Box<models::SerializerProperties>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl DataTypeProperties {
    pub fn new() -> DataTypeProperties {
        DataTypeProperties {
            serialization_properties: None,
            deserialization_properties: None,
            batch_properties: None,
            response_generation_properties: None,
            response_validation_properties: None,
            serializer_properties: None,
            purged_properties: None,
        }
    }
}

