/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataTypePropertyDescriptor {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "editorType", skip_serializing_if = "Option::is_none")]
    pub editor_type: Option<EditorType>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<serde_json::Value>>,
}

impl DataTypePropertyDescriptor {
    pub fn new() -> DataTypePropertyDescriptor {
        DataTypePropertyDescriptor {
            value: None,
            display_name: None,
            description: None,
            editor_type: None,
            options: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EditorType {
    #[serde(rename = "STRING")]
    String,
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "JAVASCRIPT")]
    Javascript,
    #[serde(rename = "OPTION")]
    Option,
}

impl Default for EditorType {
    fn default() -> EditorType {
        Self::String
    }
}

