/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseTask {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "confirmationMessage", skip_serializing_if = "Option::is_none")]
    pub confirmation_message: Option<String>,
    #[serde(rename = "affectedChannels", skip_serializing_if = "Option::is_none")]
    pub affected_channels: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "startDateTime", skip_serializing_if = "Option::is_none")]
    pub start_date_time: Option<String>,
}

impl DatabaseTask {
    pub fn new() -> DatabaseTask {
        DatabaseTask {
            id: None,
            status: None,
            name: None,
            description: None,
            confirmation_message: None,
            affected_channels: None,
            start_date_time: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Idle")]
    Idle,
    #[serde(rename = "Running")]
    Running,
}

impl Default for Status {
    fn default() -> Status {
        Self::Idle
    }
}

