/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefinitionPortMap {
    #[serde(rename = "map", skip_serializing_if = "Option::is_none")]
    pub map: Option<std::collections::HashMap<String, models::PortInformation>>,
}

impl DefinitionPortMap {
    pub fn new() -> DefinitionPortMap {
        DefinitionPortMap {
            map: None,
        }
    }
}

