/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeserializationProperties {
    #[serde(rename = "serializationType", skip_serializing_if = "Option::is_none")]
    pub serialization_type: Option<SerializationType>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "propertyDescriptors", skip_serializing_if = "Option::is_none")]
    pub property_descriptors: Option<std::collections::HashMap<String, models::DataTypePropertyDescriptor>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl DeserializationProperties {
    pub fn new() -> DeserializationProperties {
        DeserializationProperties {
            serialization_type: None,
            properties: None,
            property_descriptors: None,
            purged_properties: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SerializationType {
    #[serde(rename = "RAW")]
    Raw,
    #[serde(rename = "XML")]
    Xml,
    #[serde(rename = "JSON")]
    Json,
}

impl Default for SerializationType {
    fn default() -> SerializationType {
        Self::Raw
    }
}

