/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DriverInfo {
    #[serde(rename = "className", skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    #[serde(rename = "selectLimit", skip_serializing_if = "Option::is_none")]
    pub select_limit: Option<String>,
    #[serde(rename = "alternativeClassNames", skip_serializing_if = "Option::is_none")]
    pub alternative_class_names: Option<Vec<String>>,
}

impl DriverInfo {
    pub fn new() -> DriverInfo {
        DriverInfo {
            class_name: None,
            name: None,
            template: None,
            select_limit: None,
            alternative_class_names: None,
        }
    }
}

