/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EncryptionSettings {
    #[serde(rename = "encryptExport", skip_serializing_if = "Option::is_none")]
    pub encrypt_export: Option<bool>,
    #[serde(rename = "encryptProperties", skip_serializing_if = "Option::is_none")]
    pub encrypt_properties: Option<bool>,
    #[serde(rename = "encryptionAlgorithm", skip_serializing_if = "Option::is_none")]
    pub encryption_algorithm: Option<String>,
    #[serde(rename = "encryptionCharset", skip_serializing_if = "Option::is_none")]
    pub encryption_charset: Option<String>,
    #[serde(rename = "encryptionFallbackAlgorithm", skip_serializing_if = "Option::is_none")]
    pub encryption_fallback_algorithm: Option<String>,
    #[serde(rename = "encryptionFallbackCharset", skip_serializing_if = "Option::is_none")]
    pub encryption_fallback_charset: Option<String>,
    #[serde(rename = "encryptionKeyLength", skip_serializing_if = "Option::is_none")]
    pub encryption_key_length: Option<i32>,
    #[serde(rename = "digestAlgorithm", skip_serializing_if = "Option::is_none")]
    pub digest_algorithm: Option<String>,
    #[serde(rename = "digestSaltSize", skip_serializing_if = "Option::is_none")]
    pub digest_salt_size: Option<i32>,
    #[serde(rename = "digestIterations", skip_serializing_if = "Option::is_none")]
    pub digest_iterations: Option<i32>,
    #[serde(rename = "digestUsePBE", skip_serializing_if = "Option::is_none")]
    pub digest_use_pbe: Option<bool>,
    #[serde(rename = "digestKeySize", skip_serializing_if = "Option::is_none")]
    pub digest_key_size: Option<i32>,
    #[serde(rename = "digestFallbackAlgorithm", skip_serializing_if = "Option::is_none")]
    pub digest_fallback_algorithm: Option<String>,
    #[serde(rename = "digestFallbackSaltSize", skip_serializing_if = "Option::is_none")]
    pub digest_fallback_salt_size: Option<i32>,
    #[serde(rename = "digestFallbackIterations", skip_serializing_if = "Option::is_none")]
    pub digest_fallback_iterations: Option<i32>,
    #[serde(rename = "digestFallbackUsePBE", skip_serializing_if = "Option::is_none")]
    pub digest_fallback_use_pbe: Option<bool>,
    #[serde(rename = "digestFallbackKeySize", skip_serializing_if = "Option::is_none")]
    pub digest_fallback_key_size: Option<i32>,
    #[serde(rename = "securityProvider", skip_serializing_if = "Option::is_none")]
    pub security_provider: Option<String>,
    #[serde(rename = "secretKey", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<Vec<String>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "encryptionBaseAlgorithm", skip_serializing_if = "Option::is_none")]
    pub encryption_base_algorithm: Option<String>,
}

impl EncryptionSettings {
    pub fn new() -> EncryptionSettings {
        EncryptionSettings {
            encrypt_export: None,
            encrypt_properties: None,
            encryption_algorithm: None,
            encryption_charset: None,
            encryption_fallback_algorithm: None,
            encryption_fallback_charset: None,
            encryption_key_length: None,
            digest_algorithm: None,
            digest_salt_size: None,
            digest_iterations: None,
            digest_use_pbe: None,
            digest_key_size: None,
            digest_fallback_algorithm: None,
            digest_fallback_salt_size: None,
            digest_fallback_iterations: None,
            digest_fallback_use_pbe: None,
            digest_fallback_key_size: None,
            security_provider: None,
            secret_key: None,
            properties: None,
            encryption_base_algorithm: None,
        }
    }
}

