/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventFilter {
    #[serde(rename = "maxEventId", skip_serializing_if = "Option::is_none")]
    pub max_event_id: Option<i32>,
    #[serde(rename = "minEventId", skip_serializing_if = "Option::is_none")]
    pub min_event_id: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "levels", skip_serializing_if = "Option::is_none")]
    pub levels: Option<std::collections::HashSet<Levels>>,
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "outcome", skip_serializing_if = "Option::is_none")]
    pub outcome: Option<Outcome>,
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "attributeSearch", skip_serializing_if = "Option::is_none")]
    pub attribute_search: Option<String>,
    #[serde(rename = "ipAddress", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
    #[serde(rename = "serverId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
}

impl EventFilter {
    pub fn new() -> EventFilter {
        EventFilter {
            max_event_id: None,
            min_event_id: None,
            id: None,
            levels: None,
            start_date: None,
            end_date: None,
            name: None,
            outcome: None,
            user_id: None,
            attribute_search: None,
            ip_address: None,
            server_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Levels {
    #[serde(rename = "INFORMATION")]
    Information,
    #[serde(rename = "WARNING")]
    Warning,
    #[serde(rename = "ERROR")]
    Error,
}

impl Default for Levels {
    fn default() -> Levels {
        Self::Information
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Outcome {
    #[serde(rename = "SUCCESS")]
    Success,
    #[serde(rename = "FAILURE")]
    Failure,
}

impl Default for Outcome {
    fn default() -> Outcome {
        Self::Success
    }
}

