/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileDispatcherProperties {
    #[serde(rename = "pluginProperties", skip_serializing_if = "Option::is_none")]
    pub plugin_properties: Option<Vec<models::ConnectorPluginProperties>>,
    #[serde(rename = "destinationConnectorProperties", skip_serializing_if = "Option::is_none")]
    pub destination_connector_properties: Option<Box<models::DestinationConnectorProperties>>,
    #[serde(rename = "scheme", skip_serializing_if = "Option::is_none")]
    pub scheme: Option<Scheme>,
    #[serde(rename = "schemeProperties", skip_serializing_if = "Option::is_none")]
    pub scheme_properties: Option<Box<models::SchemeProperties>>,
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "outputPattern", skip_serializing_if = "Option::is_none")]
    pub output_pattern: Option<String>,
    #[serde(rename = "anonymous", skip_serializing_if = "Option::is_none")]
    pub anonymous: Option<bool>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
    #[serde(rename = "keepConnectionOpen", skip_serializing_if = "Option::is_none")]
    pub keep_connection_open: Option<bool>,
    #[serde(rename = "maxIdleTime", skip_serializing_if = "Option::is_none")]
    pub max_idle_time: Option<String>,
    #[serde(rename = "secure", skip_serializing_if = "Option::is_none")]
    pub secure: Option<bool>,
    #[serde(rename = "passive", skip_serializing_if = "Option::is_none")]
    pub passive: Option<bool>,
    #[serde(rename = "validateConnection", skip_serializing_if = "Option::is_none")]
    pub validate_connection: Option<bool>,
    #[serde(rename = "outputAppend", skip_serializing_if = "Option::is_none")]
    pub output_append: Option<bool>,
    #[serde(rename = "errorOnExists", skip_serializing_if = "Option::is_none")]
    pub error_on_exists: Option<bool>,
    #[serde(rename = "temporary", skip_serializing_if = "Option::is_none")]
    pub temporary: Option<bool>,
    #[serde(rename = "binary", skip_serializing_if = "Option::is_none")]
    pub binary: Option<bool>,
    #[serde(rename = "charsetEncoding", skip_serializing_if = "Option::is_none")]
    pub charset_encoding: Option<String>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl FileDispatcherProperties {
    pub fn new() -> FileDispatcherProperties {
        FileDispatcherProperties {
            plugin_properties: None,
            destination_connector_properties: None,
            scheme: None,
            scheme_properties: None,
            host: None,
            output_pattern: None,
            anonymous: None,
            username: None,
            password: None,
            timeout: None,
            keep_connection_open: None,
            max_idle_time: None,
            secure: None,
            passive: None,
            validate_connection: None,
            output_append: None,
            error_on_exists: None,
            temporary: None,
            binary: None,
            charset_encoding: None,
            template: None,
            name: None,
            protocol: None,
            purged_properties: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scheme {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "ftp")]
    Ftp,
    #[serde(rename = "sftp")]
    Sftp,
    #[serde(rename = "Amazon S3")]
    AmazonS3,
    #[serde(rename = "smb")]
    Smb,
    #[serde(rename = "webdav")]
    Webdav,
}

impl Default for Scheme {
    fn default() -> Scheme {
        Self::File
    }
}

