/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileReceiverProperties {
    #[serde(rename = "pluginProperties", skip_serializing_if = "Option::is_none")]
    pub plugin_properties: Option<Vec<models::ConnectorPluginProperties>>,
    #[serde(rename = "pollConnectorProperties", skip_serializing_if = "Option::is_none")]
    pub poll_connector_properties: Option<Box<models::PollConnectorProperties>>,
    #[serde(rename = "sourceConnectorProperties", skip_serializing_if = "Option::is_none")]
    pub source_connector_properties: Option<Box<models::SourceConnectorProperties>>,
    #[serde(rename = "scheme", skip_serializing_if = "Option::is_none")]
    pub scheme: Option<Scheme>,
    #[serde(rename = "schemeProperties", skip_serializing_if = "Option::is_none")]
    pub scheme_properties: Option<Box<models::SchemeProperties>>,
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "fileFilter", skip_serializing_if = "Option::is_none")]
    pub file_filter: Option<String>,
    #[serde(rename = "regex", skip_serializing_if = "Option::is_none")]
    pub regex: Option<bool>,
    #[serde(rename = "directoryRecursion", skip_serializing_if = "Option::is_none")]
    pub directory_recursion: Option<bool>,
    #[serde(rename = "ignoreDot", skip_serializing_if = "Option::is_none")]
    pub ignore_dot: Option<bool>,
    #[serde(rename = "anonymous", skip_serializing_if = "Option::is_none")]
    pub anonymous: Option<bool>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
    #[serde(rename = "secure", skip_serializing_if = "Option::is_none")]
    pub secure: Option<bool>,
    #[serde(rename = "passive", skip_serializing_if = "Option::is_none")]
    pub passive: Option<bool>,
    #[serde(rename = "validateConnection", skip_serializing_if = "Option::is_none")]
    pub validate_connection: Option<bool>,
    #[serde(rename = "afterProcessingAction", skip_serializing_if = "Option::is_none")]
    pub after_processing_action: Option<AfterProcessingAction>,
    #[serde(rename = "moveToDirectory", skip_serializing_if = "Option::is_none")]
    pub move_to_directory: Option<String>,
    #[serde(rename = "moveToFileName", skip_serializing_if = "Option::is_none")]
    pub move_to_file_name: Option<String>,
    #[serde(rename = "errorReadingAction", skip_serializing_if = "Option::is_none")]
    pub error_reading_action: Option<ErrorReadingAction>,
    #[serde(rename = "errorResponseAction", skip_serializing_if = "Option::is_none")]
    pub error_response_action: Option<ErrorResponseAction>,
    #[serde(rename = "errorMoveToDirectory", skip_serializing_if = "Option::is_none")]
    pub error_move_to_directory: Option<String>,
    #[serde(rename = "errorMoveToFileName", skip_serializing_if = "Option::is_none")]
    pub error_move_to_file_name: Option<String>,
    #[serde(rename = "checkFileAge", skip_serializing_if = "Option::is_none")]
    pub check_file_age: Option<bool>,
    #[serde(rename = "fileAge", skip_serializing_if = "Option::is_none")]
    pub file_age: Option<String>,
    #[serde(rename = "fileSizeMinimum", skip_serializing_if = "Option::is_none")]
    pub file_size_minimum: Option<String>,
    #[serde(rename = "fileSizeMaximum", skip_serializing_if = "Option::is_none")]
    pub file_size_maximum: Option<String>,
    #[serde(rename = "ignoreFileSizeMaximum", skip_serializing_if = "Option::is_none")]
    pub ignore_file_size_maximum: Option<bool>,
    #[serde(rename = "sortBy", skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    #[serde(rename = "binary", skip_serializing_if = "Option::is_none")]
    pub binary: Option<bool>,
    #[serde(rename = "charsetEncoding", skip_serializing_if = "Option::is_none")]
    pub charset_encoding: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl FileReceiverProperties {
    pub fn new() -> FileReceiverProperties {
        FileReceiverProperties {
            plugin_properties: None,
            poll_connector_properties: None,
            source_connector_properties: None,
            scheme: None,
            scheme_properties: None,
            host: None,
            file_filter: None,
            regex: None,
            directory_recursion: None,
            ignore_dot: None,
            anonymous: None,
            username: None,
            password: None,
            timeout: None,
            secure: None,
            passive: None,
            validate_connection: None,
            after_processing_action: None,
            move_to_directory: None,
            move_to_file_name: None,
            error_reading_action: None,
            error_response_action: None,
            error_move_to_directory: None,
            error_move_to_file_name: None,
            check_file_age: None,
            file_age: None,
            file_size_minimum: None,
            file_size_maximum: None,
            ignore_file_size_maximum: None,
            sort_by: None,
            binary: None,
            charset_encoding: None,
            name: None,
            protocol: None,
            purged_properties: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scheme {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "ftp")]
    Ftp,
    #[serde(rename = "sftp")]
    Sftp,
    #[serde(rename = "Amazon S3")]
    AmazonS3,
    #[serde(rename = "smb")]
    Smb,
    #[serde(rename = "webdav")]
    Webdav,
}

impl Default for Scheme {
    fn default() -> Scheme {
        Self::File
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AfterProcessingAction {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Move")]
    Move,
    #[serde(rename = "Delete")]
    Delete,
    #[serde(rename = "After Processing Action")]
    AfterProcessingAction,
}

impl Default for AfterProcessingAction {
    fn default() -> AfterProcessingAction {
        Self::None
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorReadingAction {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Move")]
    Move,
    #[serde(rename = "Delete")]
    Delete,
    #[serde(rename = "After Processing Action")]
    AfterProcessingAction,
}

impl Default for ErrorReadingAction {
    fn default() -> ErrorReadingAction {
        Self::None
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorResponseAction {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Move")]
    Move,
    #[serde(rename = "Delete")]
    Delete,
    #[serde(rename = "After Processing Action")]
    AfterProcessingAction,
}

impl Default for ErrorResponseAction {
    fn default() -> ErrorResponseAction {
        Self::None
    }
}

