/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Filter {
    #[serde(rename = "elements", skip_serializing_if = "Option::is_none")]
    pub elements: Option<Vec<models::Rule>>,
    #[serde(rename = "enabledElements", skip_serializing_if = "Option::is_none")]
    pub enabled_elements: Option<Vec<models::Rule>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl Filter {
    pub fn new() -> Filter {
        Filter {
            elements: None,
            enabled_elements: None,
            purged_properties: None,
        }
    }
}

