/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpDispatcherProperties {
    #[serde(rename = "pluginProperties", skip_serializing_if = "Option::is_none")]
    pub plugin_properties: Option<Vec<models::ConnectorPluginProperties>>,
    #[serde(rename = "destinationConnectorProperties", skip_serializing_if = "Option::is_none")]
    pub destination_connector_properties: Option<Box<models::DestinationConnectorProperties>>,
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "useProxyServer", skip_serializing_if = "Option::is_none")]
    pub use_proxy_server: Option<bool>,
    #[serde(rename = "proxyAddress", skip_serializing_if = "Option::is_none")]
    pub proxy_address: Option<String>,
    #[serde(rename = "proxyPort", skip_serializing_if = "Option::is_none")]
    pub proxy_port: Option<String>,
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    #[serde(rename = "useHeadersVariable", skip_serializing_if = "Option::is_none")]
    pub use_headers_variable: Option<bool>,
    #[serde(rename = "headersVariable", skip_serializing_if = "Option::is_none")]
    pub headers_variable: Option<String>,
    #[serde(rename = "useParametersVariable", skip_serializing_if = "Option::is_none")]
    pub use_parameters_variable: Option<bool>,
    #[serde(rename = "parametersVariable", skip_serializing_if = "Option::is_none")]
    pub parameters_variable: Option<String>,
    #[serde(rename = "responseXmlBody", skip_serializing_if = "Option::is_none")]
    pub response_xml_body: Option<bool>,
    #[serde(rename = "responseParseMultipart", skip_serializing_if = "Option::is_none")]
    pub response_parse_multipart: Option<bool>,
    #[serde(rename = "responseIncludeMetadata", skip_serializing_if = "Option::is_none")]
    pub response_include_metadata: Option<bool>,
    #[serde(rename = "responseBinaryMimeTypes", skip_serializing_if = "Option::is_none")]
    pub response_binary_mime_types: Option<String>,
    #[serde(rename = "responseBinaryMimeTypesRegex", skip_serializing_if = "Option::is_none")]
    pub response_binary_mime_types_regex: Option<bool>,
    #[serde(rename = "multipart", skip_serializing_if = "Option::is_none")]
    pub multipart: Option<bool>,
    #[serde(rename = "useAuthentication", skip_serializing_if = "Option::is_none")]
    pub use_authentication: Option<bool>,
    #[serde(rename = "authenticationType", skip_serializing_if = "Option::is_none")]
    pub authentication_type: Option<String>,
    #[serde(rename = "usePreemptiveAuthentication", skip_serializing_if = "Option::is_none")]
    pub use_preemptive_authentication: Option<bool>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(rename = "dataTypeBinary", skip_serializing_if = "Option::is_none")]
    pub data_type_binary: Option<bool>,
    #[serde(rename = "charset", skip_serializing_if = "Option::is_none")]
    pub charset: Option<String>,
    #[serde(rename = "socketTimeout", skip_serializing_if = "Option::is_none")]
    pub socket_timeout: Option<String>,
    #[serde(rename = "parametersMap", skip_serializing_if = "Option::is_none")]
    pub parameters_map: Option<std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "headersMap", skip_serializing_if = "Option::is_none")]
    pub headers_map: Option<std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl HttpDispatcherProperties {
    pub fn new() -> HttpDispatcherProperties {
        HttpDispatcherProperties {
            plugin_properties: None,
            destination_connector_properties: None,
            host: None,
            use_proxy_server: None,
            proxy_address: None,
            proxy_port: None,
            method: None,
            use_headers_variable: None,
            headers_variable: None,
            use_parameters_variable: None,
            parameters_variable: None,
            response_xml_body: None,
            response_parse_multipart: None,
            response_include_metadata: None,
            response_binary_mime_types: None,
            response_binary_mime_types_regex: None,
            multipart: None,
            use_authentication: None,
            authentication_type: None,
            use_preemptive_authentication: None,
            username: None,
            password: None,
            content: None,
            content_type: None,
            data_type_binary: None,
            charset: None,
            socket_timeout: None,
            parameters_map: None,
            headers_map: None,
            name: None,
            protocol: None,
            purged_properties: None,
        }
    }
}

