/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MapContent {
    #[serde(rename = "encrypted", skip_serializing_if = "Option::is_none")]
    pub encrypted: Option<bool>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<serde_json::Value>,
    #[serde(rename = "persisted", skip_serializing_if = "Option::is_none")]
    pub persisted: Option<bool>,
    #[serde(rename = "map", skip_serializing_if = "Option::is_none")]
    pub map: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl MapContent {
    pub fn new() -> MapContent {
        MapContent {
            encrypted: None,
            content: None,
            persisted: None,
            map: None,
        }
    }
}

