/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageFilter {
    #[serde(rename = "maxMessageId", skip_serializing_if = "Option::is_none")]
    pub max_message_id: Option<i64>,
    #[serde(rename = "minMessageId", skip_serializing_if = "Option::is_none")]
    pub min_message_id: Option<i64>,
    #[serde(rename = "originalIdUpper", skip_serializing_if = "Option::is_none")]
    pub original_id_upper: Option<i64>,
    #[serde(rename = "originalIdLower", skip_serializing_if = "Option::is_none")]
    pub original_id_lower: Option<i64>,
    #[serde(rename = "importIdUpper", skip_serializing_if = "Option::is_none")]
    pub import_id_upper: Option<i64>,
    #[serde(rename = "importIdLower", skip_serializing_if = "Option::is_none")]
    pub import_id_lower: Option<i64>,
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "textSearch", skip_serializing_if = "Option::is_none")]
    pub text_search: Option<String>,
    #[serde(rename = "textSearchRegex", skip_serializing_if = "Option::is_none")]
    pub text_search_regex: Option<bool>,
    #[serde(rename = "statuses", skip_serializing_if = "Option::is_none")]
    pub statuses: Option<std::collections::HashSet<Statuses>>,
    #[serde(
        rename = "includedMetaDataIds",
        skip_serializing_if = "Option::is_none"
    )]
    pub included_meta_data_ids: Option<Vec<i32>>,
    #[serde(
        rename = "excludedMetaDataIds",
        skip_serializing_if = "Option::is_none"
    )]
    pub excluded_meta_data_ids: Option<Vec<i32>>,
    #[serde(rename = "serverId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(rename = "contentSearch", skip_serializing_if = "Option::is_none")]
    pub content_search: Option<Vec<models::ContentSearchElement>>,
    #[serde(rename = "metaDataSearch", skip_serializing_if = "Option::is_none")]
    pub meta_data_search: Option<Vec<models::MetaDataSearchElement>>,
    #[serde(
        rename = "textSearchMetaDataColumns",
        skip_serializing_if = "Option::is_none"
    )]
    pub text_search_meta_data_columns: Option<Vec<String>>,
    #[serde(rename = "sendAttemptsLower", skip_serializing_if = "Option::is_none")]
    pub send_attempts_lower: Option<i32>,
    #[serde(rename = "sendAttemptsUpper", skip_serializing_if = "Option::is_none")]
    pub send_attempts_upper: Option<i32>,
    #[serde(rename = "attachment", skip_serializing_if = "Option::is_none")]
    pub attachment: Option<bool>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
}

impl MessageFilter {
    pub fn new() -> MessageFilter {
        MessageFilter {
            max_message_id: None,
            min_message_id: None,
            original_id_upper: None,
            original_id_lower: None,
            import_id_upper: None,
            import_id_lower: None,
            start_date: None,
            end_date: None,
            text_search: None,
            text_search_regex: None,
            statuses: None,
            included_meta_data_ids: None,
            excluded_meta_data_ids: None,
            server_id: None,
            content_search: None,
            meta_data_search: None,
            text_search_meta_data_columns: None,
            send_attempts_lower: None,
            send_attempts_upper: None,
            attachment: None,
            error: None,
        }
    }
}

impl std::fmt::Display for MessageFilter {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            serde_json::to_string(self).map_err(|_| std::fmt::Error)?
        )
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Statuses {
    #[serde(rename = "RECEIVED")]
    Received,
    #[serde(rename = "FILTERED")]
    Filtered,
    #[serde(rename = "TRANSFORMED")]
    Transformed,
    #[serde(rename = "SENT")]
    Sent,
    #[serde(rename = "QUEUED")]
    Queued,
    #[serde(rename = "ERROR")]
    Error,
    #[serde(rename = "PENDING")]
    Pending,
}

impl Default for Statuses {
    fn default() -> Statuses {
        Self::Received
    }
}
