/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageContent {
    #[serde(rename = "encrypted", skip_serializing_if = "Option::is_none")]
    pub encrypted: Option<bool>,
    #[serde(rename = "channelId", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "messageId", skip_serializing_if = "Option::is_none")]
    pub message_id: Option<i64>,
    #[serde(rename = "metaDataId", skip_serializing_if = "Option::is_none")]
    pub meta_data_id: Option<i32>,
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<ContentType>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "dataType", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<String>,
}

impl MessageContent {
    pub fn new() -> MessageContent {
        MessageContent {
            encrypted: None,
            channel_id: None,
            message_id: None,
            meta_data_id: None,
            content_type: None,
            content: None,
            data_type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentType {
    #[serde(rename = "Raw")]
    Raw,
    #[serde(rename = "Processed Raw")]
    ProcessedRaw,
    #[serde(rename = "Transformed")]
    Transformed,
    #[serde(rename = "Encoded")]
    Encoded,
    #[serde(rename = "Sent")]
    Sent,
    #[serde(rename = "Response")]
    Response,
    #[serde(rename = "Response Transformed")]
    ResponseTransformed,
    #[serde(rename = "Processed Response")]
    ProcessedResponse,
    #[serde(rename = "Connector Map")]
    ConnectorMap,
    #[serde(rename = "Channel Map")]
    ChannelMap,
    #[serde(rename = "Response Map")]
    ResponseMap,
    #[serde(rename = "Processing Error")]
    ProcessingError,
    #[serde(rename = "Postprocessor Error")]
    PostprocessorError,
    #[serde(rename = "Response Error")]
    ResponseError,
    #[serde(rename = "Source Map")]
    SourceMap,
}

impl Default for ContentType {
    fn default() -> ContentType {
        Self::Raw
    }
}

