/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageWriterOptions {
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<ContentType>,
    #[serde(rename = "destinationContent", skip_serializing_if = "Option::is_none")]
    pub destination_content: Option<bool>,
    #[serde(rename = "encrypt", skip_serializing_if = "Option::is_none")]
    pub encrypt: Option<bool>,
    #[serde(rename = "includeAttachments", skip_serializing_if = "Option::is_none")]
    pub include_attachments: Option<bool>,
    #[serde(rename = "baseFolder", skip_serializing_if = "Option::is_none")]
    pub base_folder: Option<String>,
    #[serde(rename = "rootFolder", skip_serializing_if = "Option::is_none")]
    pub root_folder: Option<String>,
    #[serde(rename = "filePattern", skip_serializing_if = "Option::is_none")]
    pub file_pattern: Option<String>,
    #[serde(rename = "archiveFileName", skip_serializing_if = "Option::is_none")]
    pub archive_file_name: Option<String>,
    #[serde(rename = "archiveFormat", skip_serializing_if = "Option::is_none")]
    pub archive_format: Option<String>,
    #[serde(rename = "compressFormat", skip_serializing_if = "Option::is_none")]
    pub compress_format: Option<String>,
    #[serde(rename = "passwordEnabled", skip_serializing_if = "Option::is_none")]
    pub password_enabled: Option<bool>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "encryptionType", skip_serializing_if = "Option::is_none")]
    pub encryption_type: Option<EncryptionType>,
}

impl MessageWriterOptions {
    pub fn new() -> MessageWriterOptions {
        MessageWriterOptions {
            content_type: None,
            destination_content: None,
            encrypt: None,
            include_attachments: None,
            base_folder: None,
            root_folder: None,
            file_pattern: None,
            archive_file_name: None,
            archive_format: None,
            compress_format: None,
            password_enabled: None,
            password: None,
            encryption_type: None,
        }
    }
}

impl std::fmt::Display for MessageWriterOptions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            serde_json::to_string(self).map_err(|_| std::fmt::Error)?
        )
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentType {
    #[serde(rename = "Raw")]
    Raw,
    #[serde(rename = "Processed Raw")]
    ProcessedRaw,
    #[serde(rename = "Transformed")]
    Transformed,
    #[serde(rename = "Encoded")]
    Encoded,
    #[serde(rename = "Sent")]
    Sent,
    #[serde(rename = "Response")]
    Response,
    #[serde(rename = "Response Transformed")]
    ResponseTransformed,
    #[serde(rename = "Processed Response")]
    ProcessedResponse,
    #[serde(rename = "Connector Map")]
    ConnectorMap,
    #[serde(rename = "Channel Map")]
    ChannelMap,
    #[serde(rename = "Response Map")]
    ResponseMap,
    #[serde(rename = "Processing Error")]
    ProcessingError,
    #[serde(rename = "Postprocessor Error")]
    PostprocessorError,
    #[serde(rename = "Response Error")]
    ResponseError,
    #[serde(rename = "Source Map")]
    SourceMap,
}

impl Default for ContentType {
    fn default() -> ContentType {
        Self::Raw
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EncryptionType {
    #[serde(rename = "STANDARD")]
    Standard,
    #[serde(rename = "AES128")]
    Aes128,
    #[serde(rename = "AES256")]
    Aes256,
}

impl Default for EncryptionType {
    fn default() -> EncryptionType {
        Self::Standard
    }
}
