/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    #[serde(rename = "messageId", skip_serializing_if = "Option::is_none")]
    pub message_id: Option<i64>,
    #[serde(rename = "serverId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(rename = "channelId", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "channelName", skip_serializing_if = "Option::is_none")]
    pub channel_name: Option<String>,
    #[serde(rename = "receivedDate", skip_serializing_if = "Option::is_none")]
    pub received_date: Option<String>,
    #[serde(rename = "processed", skip_serializing_if = "Option::is_none")]
    pub processed: Option<bool>,
    #[serde(rename = "originalId", skip_serializing_if = "Option::is_none")]
    pub original_id: Option<i64>,
    #[serde(rename = "importId", skip_serializing_if = "Option::is_none")]
    pub import_id: Option<i64>,
    #[serde(rename = "importChannelId", skip_serializing_if = "Option::is_none")]
    pub import_channel_id: Option<String>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::Attachment>>,
    #[serde(rename = "connectorMessages", skip_serializing_if = "Option::is_none")]
    pub connector_messages: Option<std::collections::HashMap<String, models::ConnectorMessage>>,
    #[serde(rename = "mergedConnectorMessage", skip_serializing_if = "Option::is_none")]
    pub merged_connector_message: Option<Box<models::ConnectorMessage>>,
}

impl Message {
    pub fn new() -> Message {
        Message {
            message_id: None,
            server_id: None,
            channel_id: None,
            channel_name: None,
            received_date: None,
            processed: None,
            original_id: None,
            import_id: None,
            import_channel_id: None,
            attachments: None,
            connector_messages: None,
            merged_connector_message: None,
        }
    }
}

