/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetaDataSearchElement {
    #[serde(rename = "columnName", skip_serializing_if = "Option::is_none")]
    pub column_name: Option<String>,
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    #[serde(rename = "ignoreCase", skip_serializing_if = "Option::is_none")]
    pub ignore_case: Option<bool>,
}

impl MetaDataSearchElement {
    pub fn new() -> MetaDataSearchElement {
        MetaDataSearchElement {
            column_name: None,
            operator: None,
            value: None,
            ignore_case: None,
        }
    }
}

