/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordRequirements {
    #[serde(rename = "minLength", skip_serializing_if = "Option::is_none")]
    pub min_length: Option<i32>,
    #[serde(rename = "minUpper", skip_serializing_if = "Option::is_none")]
    pub min_upper: Option<i32>,
    #[serde(rename = "minLower", skip_serializing_if = "Option::is_none")]
    pub min_lower: Option<i32>,
    #[serde(rename = "minNumeric", skip_serializing_if = "Option::is_none")]
    pub min_numeric: Option<i32>,
    #[serde(rename = "minSpecial", skip_serializing_if = "Option::is_none")]
    pub min_special: Option<i32>,
    #[serde(rename = "retryLimit", skip_serializing_if = "Option::is_none")]
    pub retry_limit: Option<i32>,
    #[serde(rename = "lockoutPeriod", skip_serializing_if = "Option::is_none")]
    pub lockout_period: Option<i32>,
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<i32>,
    #[serde(rename = "gracePeriod", skip_serializing_if = "Option::is_none")]
    pub grace_period: Option<i32>,
    #[serde(rename = "reusePeriod", skip_serializing_if = "Option::is_none")]
    pub reuse_period: Option<i32>,
    #[serde(rename = "reuseLimit", skip_serializing_if = "Option::is_none")]
    pub reuse_limit: Option<i32>,
}

impl PasswordRequirements {
    pub fn new() -> PasswordRequirements {
        PasswordRequirements {
            min_length: None,
            min_upper: None,
            min_lower: None,
            min_numeric: None,
            min_special: None,
            retry_limit: None,
            lockout_period: None,
            expiration: None,
            grace_period: None,
            reuse_period: None,
            reuse_limit: None,
        }
    }
}

