/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginMetaData {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(rename = "mirthVersion", skip_serializing_if = "Option::is_none")]
    pub mirth_version: Option<String>,
    #[serde(rename = "pluginVersion", skip_serializing_if = "Option::is_none")]
    pub plugin_version: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "apiProviders", skip_serializing_if = "Option::is_none")]
    pub api_providers: Option<Vec<models::ApiProvider>>,
    #[serde(rename = "libraries", skip_serializing_if = "Option::is_none")]
    pub libraries: Option<Vec<models::ExtensionLibrary>>,
    #[serde(rename = "templateClassName", skip_serializing_if = "Option::is_none")]
    pub template_class_name: Option<String>,
    #[serde(rename = "userutilPackages", skip_serializing_if = "Option::is_none")]
    pub userutil_packages: Option<Vec<String>>,
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<bool>,
    #[serde(rename = "serverClasses", skip_serializing_if = "Option::is_none")]
    pub server_classes: Option<Vec<models::PluginClass>>,
    #[serde(rename = "clientClasses", skip_serializing_if = "Option::is_none")]
    pub client_classes: Option<Vec<models::PluginClass>>,
    #[serde(rename = "controllerClasses", skip_serializing_if = "Option::is_none")]
    pub controller_classes: Option<Vec<models::PluginClass>>,
    #[serde(rename = "migratorClass", skip_serializing_if = "Option::is_none")]
    pub migrator_class: Option<String>,
    #[serde(rename = "sqlScript", skip_serializing_if = "Option::is_none")]
    pub sql_script: Option<String>,
    #[serde(rename = "sqlMapConfigs", skip_serializing_if = "Option::is_none")]
    pub sql_map_configs: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl PluginMetaData {
    pub fn new() -> PluginMetaData {
        PluginMetaData {
            path: None,
            name: None,
            author: None,
            mirth_version: None,
            plugin_version: None,
            url: None,
            description: None,
            api_providers: None,
            libraries: None,
            template_class_name: None,
            userutil_packages: None,
            notify: None,
            server_classes: None,
            client_classes: None,
            controller_classes: None,
            migrator_class: None,
            sql_script: None,
            sql_map_configs: None,
            purged_properties: None,
        }
    }
}

