/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PollConnectorProperties {
    #[serde(rename = "pollingType", skip_serializing_if = "Option::is_none")]
    pub polling_type: Option<PollingType>,
    #[serde(rename = "pollOnStart", skip_serializing_if = "Option::is_none")]
    pub poll_on_start: Option<bool>,
    #[serde(rename = "pollingFrequency", skip_serializing_if = "Option::is_none")]
    pub polling_frequency: Option<i32>,
    #[serde(rename = "pollingHour", skip_serializing_if = "Option::is_none")]
    pub polling_hour: Option<i32>,
    #[serde(rename = "pollingMinute", skip_serializing_if = "Option::is_none")]
    pub polling_minute: Option<i32>,
    #[serde(rename = "cronJobs", skip_serializing_if = "Option::is_none")]
    pub cron_jobs: Option<Vec<models::CronProperty>>,
    #[serde(rename = "pollConnectorPropertiesAdvanced", skip_serializing_if = "Option::is_none")]
    pub poll_connector_properties_advanced: Option<Box<models::PollConnectorPropertiesAdvanced>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl PollConnectorProperties {
    pub fn new() -> PollConnectorProperties {
        PollConnectorProperties {
            polling_type: None,
            poll_on_start: None,
            polling_frequency: None,
            polling_hour: None,
            polling_minute: None,
            cron_jobs: None,
            poll_connector_properties_advanced: None,
            purged_properties: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PollingType {
    #[serde(rename = "INTERVAL")]
    Interval,
    #[serde(rename = "TIME")]
    Time,
    #[serde(rename = "CRON")]
    Cron,
}

impl Default for PollingType {
    fn default() -> PollingType {
        Self::Interval
    }
}

