/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PollConnectorPropertiesAdvanced {
    #[serde(rename = "weekly", skip_serializing_if = "Option::is_none")]
    pub weekly: Option<bool>,
    #[serde(rename = "inactiveDays", skip_serializing_if = "Option::is_none")]
    pub inactive_days: Option<Vec<bool>>,
    #[serde(rename = "dayOfMonth", skip_serializing_if = "Option::is_none")]
    pub day_of_month: Option<i32>,
    #[serde(rename = "allDay", skip_serializing_if = "Option::is_none")]
    pub all_day: Option<bool>,
    #[serde(rename = "startingHour", skip_serializing_if = "Option::is_none")]
    pub starting_hour: Option<i32>,
    #[serde(rename = "startingMinute", skip_serializing_if = "Option::is_none")]
    pub starting_minute: Option<i32>,
    #[serde(rename = "endingHour", skip_serializing_if = "Option::is_none")]
    pub ending_hour: Option<i32>,
    #[serde(rename = "endingMinute", skip_serializing_if = "Option::is_none")]
    pub ending_minute: Option<i32>,
    #[serde(rename = "activeDays", skip_serializing_if = "Option::is_none")]
    pub active_days: Option<Vec<bool>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl PollConnectorPropertiesAdvanced {
    pub fn new() -> PollConnectorPropertiesAdvanced {
        PollConnectorPropertiesAdvanced {
            weekly: None,
            inactive_days: None,
            day_of_month: None,
            all_day: None,
            starting_hour: None,
            starting_minute: None,
            ending_hour: None,
            ending_minute: None,
            active_days: None,
            purged_properties: None,
        }
    }
}

