/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RawMessage {
    #[serde(rename = "overwrite", skip_serializing_if = "Option::is_none")]
    pub overwrite: Option<bool>,
    #[serde(rename = "imported", skip_serializing_if = "Option::is_none")]
    pub imported: Option<bool>,
    #[serde(rename = "originalMessageId", skip_serializing_if = "Option::is_none")]
    pub original_message_id: Option<i64>,
    #[serde(rename = "rawData", skip_serializing_if = "Option::is_none")]
    pub raw_data: Option<String>,
    #[serde(rename = "rawBytes", skip_serializing_if = "Option::is_none")]
    pub raw_bytes: Option<Vec<String>>,
    #[serde(rename = "destinationMetaDataIds", skip_serializing_if = "Option::is_none")]
    pub destination_meta_data_ids: Option<Vec<i32>>,
    #[serde(rename = "sourceMap", skip_serializing_if = "Option::is_none")]
    pub source_map: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "binary", skip_serializing_if = "Option::is_none")]
    pub binary: Option<bool>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::Attachment>>,
}

impl RawMessage {
    pub fn new() -> RawMessage {
        RawMessage {
            overwrite: None,
            imported: None,
            original_message_id: None,
            raw_data: None,
            raw_bytes: None,
            destination_meta_data_ids: None,
            source_map: None,
            binary: None,
            attachments: None,
        }
    }
}

