/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceProperties {
    #[serde(rename = "pluginPointName", skip_serializing_if = "Option::is_none")]
    pub plugin_point_name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "includeWithGlobalScripts", skip_serializing_if = "Option::is_none")]
    pub include_with_global_scripts: Option<bool>,
    #[serde(rename = "loadParentFirst", skip_serializing_if = "Option::is_none")]
    pub load_parent_first: Option<bool>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ResourceProperties {
    pub fn new() -> ResourceProperties {
        ResourceProperties {
            plugin_point_name: None,
            r#type: None,
            id: None,
            name: None,
            description: None,
            include_with_global_scripts: None,
            load_parent_first: None,
            purged_properties: None,
        }
    }
}

