/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchemeProperties {
    #[serde(rename = "summaryText", skip_serializing_if = "Option::is_none")]
    pub summary_text: Option<String>,
    #[serde(rename = "fileSchemeProperties", skip_serializing_if = "Option::is_none")]
    pub file_scheme_properties: Option<Box<models::SchemeProperties>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl SchemeProperties {
    pub fn new() -> SchemeProperties {
        SchemeProperties {
            summary_text: None,
            file_scheme_properties: None,
            purged_properties: None,
        }
    }
}

