/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SerializerProperties {
    #[serde(rename = "serializationProperties", skip_serializing_if = "Option::is_none")]
    pub serialization_properties: Option<Box<models::SerializationProperties>>,
    #[serde(rename = "deserializationProperties", skip_serializing_if = "Option::is_none")]
    pub deserialization_properties: Option<Box<models::DeserializationProperties>>,
    #[serde(rename = "batchProperties", skip_serializing_if = "Option::is_none")]
    pub batch_properties: Option<Box<models::BatchProperties>>,
}

impl SerializerProperties {
    pub fn new() -> SerializerProperties {
        SerializerProperties {
            serialization_properties: None,
            deserialization_properties: None,
            batch_properties: None,
        }
    }
}

