/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerSettings {
    #[serde(rename = "environmentName", skip_serializing_if = "Option::is_none")]
    pub environment_name: Option<String>,
    #[serde(rename = "serverName", skip_serializing_if = "Option::is_none")]
    pub server_name: Option<String>,
    #[serde(rename = "clearGlobalMap", skip_serializing_if = "Option::is_none")]
    pub clear_global_map: Option<bool>,
    #[serde(rename = "queueBufferSize", skip_serializing_if = "Option::is_none")]
    pub queue_buffer_size: Option<i32>,
    #[serde(rename = "defaultMetaDataColumns", skip_serializing_if = "Option::is_none")]
    pub default_meta_data_columns: Option<Vec<models::MetaDataColumn>>,
    #[serde(rename = "defaultAdministratorBackgroundColor", skip_serializing_if = "Option::is_none")]
    pub default_administrator_background_color: Option<Box<models::ChannelTagBackgroundColor>>,
    #[serde(rename = "smtpHost", skip_serializing_if = "Option::is_none")]
    pub smtp_host: Option<String>,
    #[serde(rename = "smtpPort", skip_serializing_if = "Option::is_none")]
    pub smtp_port: Option<String>,
    #[serde(rename = "smtpTimeout", skip_serializing_if = "Option::is_none")]
    pub smtp_timeout: Option<String>,
    #[serde(rename = "smtpFrom", skip_serializing_if = "Option::is_none")]
    pub smtp_from: Option<String>,
    #[serde(rename = "smtpSecure", skip_serializing_if = "Option::is_none")]
    pub smtp_secure: Option<String>,
    #[serde(rename = "smtpAuth", skip_serializing_if = "Option::is_none")]
    pub smtp_auth: Option<bool>,
    #[serde(rename = "smtpUsername", skip_serializing_if = "Option::is_none")]
    pub smtp_username: Option<String>,
    #[serde(rename = "smtpPassword", skip_serializing_if = "Option::is_none")]
    pub smtp_password: Option<String>,
    #[serde(rename = "loginNotificationEnabled", skip_serializing_if = "Option::is_none")]
    pub login_notification_enabled: Option<bool>,
    #[serde(rename = "loginNotificationMessage", skip_serializing_if = "Option::is_none")]
    pub login_notification_message: Option<String>,
    #[serde(rename = "administratorAutoLogoutIntervalEnabled", skip_serializing_if = "Option::is_none")]
    pub administrator_auto_logout_interval_enabled: Option<bool>,
    #[serde(rename = "administratorAutoLogoutIntervalField", skip_serializing_if = "Option::is_none")]
    pub administrator_auto_logout_interval_field: Option<i32>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ServerSettings {
    pub fn new() -> ServerSettings {
        ServerSettings {
            environment_name: None,
            server_name: None,
            clear_global_map: None,
            queue_buffer_size: None,
            default_meta_data_columns: None,
            default_administrator_background_color: None,
            smtp_host: None,
            smtp_port: None,
            smtp_timeout: None,
            smtp_from: None,
            smtp_secure: None,
            smtp_auth: None,
            smtp_username: None,
            smtp_password: None,
            login_notification_enabled: None,
            login_notification_message: None,
            administrator_auto_logout_interval_enabled: None,
            administrator_auto_logout_interval_field: None,
            properties: None,
            purged_properties: None,
        }
    }
}

