/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerLogItem {
    #[serde(rename = "serverId", skip_serializing_if = "Option::is_none")]
    pub server_id: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "threadName", skip_serializing_if = "Option::is_none")]
    pub thread_name: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "lineNumber", skip_serializing_if = "Option::is_none")]
    pub line_number: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "throwableInformation", skip_serializing_if = "Option::is_none")]
    pub throwable_information: Option<String>,
}

impl ServerLogItem {
    pub fn new() -> ServerLogItem {
        ServerLogItem {
            server_id: None,
            id: None,
            level: None,
            date: None,
            thread_name: None,
            category: None,
            line_number: None,
            message: None,
            throwable_information: None,
        }
    }
}

