/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerConfiguration {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "channelGroups", skip_serializing_if = "Option::is_none")]
    pub channel_groups: Option<Vec<models::ChannelGroup>>,
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<Vec<models::Channel>>,
    #[serde(rename = "channelTags", skip_serializing_if = "Option::is_none")]
    pub channel_tags: Option<Vec<models::ChannelTag>>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<models::User>>,
    #[serde(rename = "alerts", skip_serializing_if = "Option::is_none")]
    pub alerts: Option<Vec<models::AlertModel>>,
    #[serde(rename = "codeTemplateLibraries", skip_serializing_if = "Option::is_none")]
    pub code_template_libraries: Option<Vec<models::CodeTemplateLibrary>>,
    #[serde(rename = "serverSettings", skip_serializing_if = "Option::is_none")]
    pub server_settings: Option<Box<models::ServerSettings>>,
    #[serde(rename = "updateSettings", skip_serializing_if = "Option::is_none")]
    pub update_settings: Option<Box<models::UpdateSettings>>,
    #[serde(rename = "globalScripts", skip_serializing_if = "Option::is_none")]
    pub global_scripts: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "pluginProperties", skip_serializing_if = "Option::is_none")]
    pub plugin_properties: Option<std::collections::HashMap<String, std::collections::HashMap<String, String>>>,
    #[serde(rename = "resourceProperties", skip_serializing_if = "Option::is_none")]
    pub resource_properties: Option<Box<models::ResourcePropertiesList>>,
    #[serde(rename = "channelDependencies", skip_serializing_if = "Option::is_none")]
    pub channel_dependencies: Option<Vec<models::ChannelDependency>>,
    #[serde(rename = "configurationMap", skip_serializing_if = "Option::is_none")]
    pub configuration_map: Option<std::collections::HashMap<String, models::ConfigurationProperty>>,
}

impl ServerConfiguration {
    pub fn new() -> ServerConfiguration {
        ServerConfiguration {
            date: None,
            channel_groups: None,
            channels: None,
            channel_tags: None,
            users: None,
            alerts: None,
            code_template_libraries: None,
            server_settings: None,
            update_settings: None,
            global_scripts: None,
            plugin_properties: None,
            resource_properties: None,
            channel_dependencies: None,
            configuration_map: None,
        }
    }
}

