/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SmtpDispatcherProperties {
    #[serde(rename = "pluginProperties", skip_serializing_if = "Option::is_none")]
    pub plugin_properties: Option<Vec<models::ConnectorPluginProperties>>,
    #[serde(rename = "destinationConnectorProperties", skip_serializing_if = "Option::is_none")]
    pub destination_connector_properties: Option<Box<models::DestinationConnectorProperties>>,
    #[serde(rename = "smtpHost", skip_serializing_if = "Option::is_none")]
    pub smtp_host: Option<String>,
    #[serde(rename = "smtpPort", skip_serializing_if = "Option::is_none")]
    pub smtp_port: Option<String>,
    #[serde(rename = "overrideLocalBinding", skip_serializing_if = "Option::is_none")]
    pub override_local_binding: Option<bool>,
    #[serde(rename = "localAddress", skip_serializing_if = "Option::is_none")]
    pub local_address: Option<String>,
    #[serde(rename = "localPort", skip_serializing_if = "Option::is_none")]
    pub local_port: Option<String>,
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
    #[serde(rename = "encryption", skip_serializing_if = "Option::is_none")]
    pub encryption: Option<String>,
    #[serde(rename = "authentication", skip_serializing_if = "Option::is_none")]
    pub authentication: Option<bool>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    #[serde(rename = "cc", skip_serializing_if = "Option::is_none")]
    pub cc: Option<String>,
    #[serde(rename = "bcc", skip_serializing_if = "Option::is_none")]
    pub bcc: Option<String>,
    #[serde(rename = "replyTo", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<String>,
    #[serde(rename = "headersVariable", skip_serializing_if = "Option::is_none")]
    pub headers_variable: Option<String>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "charsetEncoding", skip_serializing_if = "Option::is_none")]
    pub charset_encoding: Option<String>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<bool>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "attachmentsVariable", skip_serializing_if = "Option::is_none")]
    pub attachments_variable: Option<String>,
    #[serde(rename = "useHeadersVariable", skip_serializing_if = "Option::is_none")]
    pub use_headers_variable: Option<bool>,
    #[serde(rename = "useAttachmentsVariable", skip_serializing_if = "Option::is_none")]
    pub use_attachments_variable: Option<bool>,
    #[serde(rename = "headersMap", skip_serializing_if = "Option::is_none")]
    pub headers_map: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "attachmentsList", skip_serializing_if = "Option::is_none")]
    pub attachments_list: Option<Vec<models::Attachment>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl SmtpDispatcherProperties {
    pub fn new() -> SmtpDispatcherProperties {
        SmtpDispatcherProperties {
            plugin_properties: None,
            destination_connector_properties: None,
            smtp_host: None,
            smtp_port: None,
            override_local_binding: None,
            local_address: None,
            local_port: None,
            timeout: None,
            encryption: None,
            authentication: None,
            username: None,
            password: None,
            to: None,
            from: None,
            cc: None,
            bcc: None,
            reply_to: None,
            headers_variable: None,
            subject: None,
            charset_encoding: None,
            html: None,
            body: None,
            attachments_variable: None,
            use_headers_variable: None,
            use_attachments_variable: None,
            headers_map: None,
            attachments_list: None,
            name: None,
            protocol: None,
            purged_properties: None,
        }
    }
}

