/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceConnectorProperties {
    #[serde(rename = "responseVariable", skip_serializing_if = "Option::is_none")]
    pub response_variable: Option<String>,
    #[serde(rename = "respondAfterProcessing", skip_serializing_if = "Option::is_none")]
    pub respond_after_processing: Option<bool>,
    #[serde(rename = "processBatch", skip_serializing_if = "Option::is_none")]
    pub process_batch: Option<bool>,
    #[serde(rename = "firstResponse", skip_serializing_if = "Option::is_none")]
    pub first_response: Option<bool>,
    #[serde(rename = "processingThreads", skip_serializing_if = "Option::is_none")]
    pub processing_threads: Option<i32>,
    #[serde(rename = "resourceIds", skip_serializing_if = "Option::is_none")]
    pub resource_ids: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "queueBufferSize", skip_serializing_if = "Option::is_none")]
    pub queue_buffer_size: Option<i32>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl SourceConnectorProperties {
    pub fn new() -> SourceConnectorProperties {
        SourceConnectorProperties {
            response_variable: None,
            respond_after_processing: None,
            process_batch: None,
            first_response: None,
            processing_threads: None,
            resource_ids: None,
            queue_buffer_size: None,
            purged_properties: None,
        }
    }
}

