/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemInfo {
    #[serde(rename = "jvmVersion", skip_serializing_if = "Option::is_none")]
    pub jvm_version: Option<String>,
    #[serde(rename = "osName", skip_serializing_if = "Option::is_none")]
    pub os_name: Option<String>,
    #[serde(rename = "osVersion", skip_serializing_if = "Option::is_none")]
    pub os_version: Option<String>,
    #[serde(rename = "osArchitecture", skip_serializing_if = "Option::is_none")]
    pub os_architecture: Option<String>,
    #[serde(rename = "dbName", skip_serializing_if = "Option::is_none")]
    pub db_name: Option<String>,
    #[serde(rename = "dbVersion", skip_serializing_if = "Option::is_none")]
    pub db_version: Option<String>,
}

impl SystemInfo {
    pub fn new() -> SystemInfo {
        SystemInfo {
            jvm_version: None,
            os_name: None,
            os_version: None,
            os_architecture: None,
            db_name: None,
            db_version: None,
        }
    }
}

