/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemStats {
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "cpuUsagePct", skip_serializing_if = "Option::is_none")]
    pub cpu_usage_pct: Option<f64>,
    #[serde(rename = "allocatedMemoryBytes", skip_serializing_if = "Option::is_none")]
    pub allocated_memory_bytes: Option<i64>,
    #[serde(rename = "freeMemoryBytes", skip_serializing_if = "Option::is_none")]
    pub free_memory_bytes: Option<i64>,
    #[serde(rename = "maxMemoryBytes", skip_serializing_if = "Option::is_none")]
    pub max_memory_bytes: Option<i64>,
    #[serde(rename = "diskFreeBytes", skip_serializing_if = "Option::is_none")]
    pub disk_free_bytes: Option<i64>,
    #[serde(rename = "diskTotalBytes", skip_serializing_if = "Option::is_none")]
    pub disk_total_bytes: Option<i64>,
}

impl SystemStats {
    pub fn new() -> SystemStats {
        SystemStats {
            timestamp: None,
            cpu_usage_pct: None,
            allocated_memory_bytes: None,
            free_memory_bytes: None,
            max_memory_bytes: None,
            disk_free_bytes: None,
            disk_total_bytes: None,
        }
    }
}

