/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransmissionModeProperties {
    #[serde(rename = "pluginPointName", skip_serializing_if = "Option::is_none")]
    pub plugin_point_name: Option<String>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl TransmissionModeProperties {
    pub fn new() -> TransmissionModeProperties {
        TransmissionModeProperties {
            plugin_point_name: None,
            purged_properties: None,
        }
    }
}

