/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transformer {
    #[serde(rename = "elements", skip_serializing_if = "Option::is_none")]
    pub elements: Option<Vec<models::Step>>,
    #[serde(rename = "inboundTemplate", skip_serializing_if = "Option::is_none")]
    pub inbound_template: Option<String>,
    #[serde(rename = "outboundTemplate", skip_serializing_if = "Option::is_none")]
    pub outbound_template: Option<String>,
    #[serde(rename = "inboundDataType", skip_serializing_if = "Option::is_none")]
    pub inbound_data_type: Option<String>,
    #[serde(rename = "outboundDataType", skip_serializing_if = "Option::is_none")]
    pub outbound_data_type: Option<String>,
    #[serde(rename = "inboundProperties", skip_serializing_if = "Option::is_none")]
    pub inbound_properties: Option<Box<models::DataTypeProperties>>,
    #[serde(rename = "outboundProperties", skip_serializing_if = "Option::is_none")]
    pub outbound_properties: Option<Box<models::DataTypeProperties>>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "enabledElements", skip_serializing_if = "Option::is_none")]
    pub enabled_elements: Option<Vec<models::Step>>,
}

impl Transformer {
    pub fn new() -> Transformer {
        Transformer {
            elements: None,
            inbound_template: None,
            outbound_template: None,
            inbound_data_type: None,
            outbound_data_type: None,
            inbound_properties: None,
            outbound_properties: None,
            purged_properties: None,
            enabled_elements: None,
        }
    }
}

