/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "industry", skip_serializing_if = "Option::is_none")]
    pub industry: Option<String>,
    #[serde(rename = "lastLogin", skip_serializing_if = "Option::is_none")]
    pub last_login: Option<String>,
    #[serde(rename = "gracePeriodStart", skip_serializing_if = "Option::is_none")]
    pub grace_period_start: Option<String>,
    #[serde(rename = "strikeCount", skip_serializing_if = "Option::is_none")]
    pub strike_count: Option<i32>,
    #[serde(rename = "lastStrikeTime", skip_serializing_if = "Option::is_none")]
    pub last_strike_time: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "stateTerritory", skip_serializing_if = "Option::is_none")]
    pub state_territory: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "userConsent", skip_serializing_if = "Option::is_none")]
    pub user_consent: Option<bool>,
}

impl User {
    pub fn new() -> User {
        User {
            id: None,
            username: None,
            email: None,
            first_name: None,
            last_name: None,
            organization: None,
            description: None,
            phone_number: None,
            industry: None,
            last_login: None,
            grace_period_start: None,
            strike_count: None,
            last_strike_time: None,
            country: None,
            state_territory: None,
            role: None,
            user_consent: None,
        }
    }
}

