/*
 * Open Integration Engine Client API
 *
 * Swagger documentation for the Open Integration Engine Client API.
 *
 * The version of the OpenAPI document: 4.5.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebServiceDispatcherProperties {
    #[serde(rename = "pluginProperties", skip_serializing_if = "Option::is_none")]
    pub plugin_properties: Option<Vec<models::ConnectorPluginProperties>>,
    #[serde(rename = "destinationConnectorProperties", skip_serializing_if = "Option::is_none")]
    pub destination_connector_properties: Option<Box<models::DestinationConnectorProperties>>,
    #[serde(rename = "wsdlUrl", skip_serializing_if = "Option::is_none")]
    pub wsdl_url: Option<String>,
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    #[serde(rename = "locationURI", skip_serializing_if = "Option::is_none")]
    pub location_uri: Option<String>,
    #[serde(rename = "socketTimeout", skip_serializing_if = "Option::is_none")]
    pub socket_timeout: Option<String>,
    #[serde(rename = "useAuthentication", skip_serializing_if = "Option::is_none")]
    pub use_authentication: Option<bool>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "envelope", skip_serializing_if = "Option::is_none")]
    pub envelope: Option<String>,
    #[serde(rename = "oneWay", skip_serializing_if = "Option::is_none")]
    pub one_way: Option<bool>,
    #[serde(rename = "headersVariable", skip_serializing_if = "Option::is_none")]
    pub headers_variable: Option<String>,
    #[serde(rename = "useMtom", skip_serializing_if = "Option::is_none")]
    pub use_mtom: Option<bool>,
    #[serde(rename = "attachmentNames", skip_serializing_if = "Option::is_none")]
    pub attachment_names: Option<Vec<String>>,
    #[serde(rename = "attachmentContents", skip_serializing_if = "Option::is_none")]
    pub attachment_contents: Option<Vec<String>>,
    #[serde(rename = "attachmentTypes", skip_serializing_if = "Option::is_none")]
    pub attachment_types: Option<Vec<String>>,
    #[serde(rename = "attachmentsVariable", skip_serializing_if = "Option::is_none")]
    pub attachments_variable: Option<String>,
    #[serde(rename = "soapAction", skip_serializing_if = "Option::is_none")]
    pub soap_action: Option<String>,
    #[serde(rename = "wsdlDefinitionMap", skip_serializing_if = "Option::is_none")]
    pub wsdl_definition_map: Option<Box<models::DefinitionServiceMap>>,
    #[serde(rename = "useHeadersVariable", skip_serializing_if = "Option::is_none")]
    pub use_headers_variable: Option<bool>,
    #[serde(rename = "useAttachmentsVariable", skip_serializing_if = "Option::is_none")]
    pub use_attachments_variable: Option<bool>,
    #[serde(rename = "headersMap", skip_serializing_if = "Option::is_none")]
    pub headers_map: Option<std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "purgedProperties", skip_serializing_if = "Option::is_none")]
    pub purged_properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl WebServiceDispatcherProperties {
    pub fn new() -> WebServiceDispatcherProperties {
        WebServiceDispatcherProperties {
            plugin_properties: None,
            destination_connector_properties: None,
            wsdl_url: None,
            service: None,
            port: None,
            operation: None,
            location_uri: None,
            socket_timeout: None,
            use_authentication: None,
            username: None,
            password: None,
            envelope: None,
            one_way: None,
            headers_variable: None,
            use_mtom: None,
            attachment_names: None,
            attachment_contents: None,
            attachment_types: None,
            attachments_variable: None,
            soap_action: None,
            wsdl_definition_map: None,
            use_headers_variable: None,
            use_attachments_variable: None,
            headers_map: None,
            name: None,
            protocol: None,
            purged_properties: None,
        }
    }
}

